src/App.tsx
src/containers/OAuth.tsx
src/content/apiDocs/oauthTechnical.mdx

Resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/717
It turns out our new markdown loader [already includes highlight.js](https://github.com/ticky/markdown-component-loader/blob/v1.1.0/src/convert.js#L104-L134) and it's not configurable, which isn't great. If this becomes on issue, it looks like the maintainer would be open to a PR to change that.
The highlighter kind of mangled some of our HTTP request blocks, so I disabled highlighting of those with the `plaintext` language.
Here's one of the bad highlights that I disabled:
And here's an example of it working nicely:

Add syntax highlighting

---

config/webpack.config.prod.js

We're using Google's workbox to manage the service worker cache for the
developer site. It can be configured to 'skipWaiting' when a new service worker
is available and have that worker immediately take over a site when its ready
instead of waiting for all open versions of the site to be closed then
replacing the service worker, which can mean users see an outdated version of
the site.
Using skipWaiting can mean the site can load initially with and outdated version
of the site JS and then have that JS replaced when the new Service Worker loads,
which can potentially cause site inconsistencies. Since we're largely just using
this page for static content at the moment, this doesn't seem like a big risk
for the tradeoff of always serving an up-to-date version, and we can re-evaluate
later …

Enable Workbox to skipWaiting when a new service worker is available

---

package-lock.json
src/actions/index.ts

It's possible to have a response without a token (ie if you're only requesting health). this change handles that.

Change page even if a token is not returned

---

package.json
tslint.ci.json
tslint.json

I've split the default tslint config and the config we run during CI tests in order to avoid developers having to change rules while developing. This opens up the possibility of pushing a PR for a set of changes that will fail the linter during CI but not locally. To me that seems annoying but less annoying than the status quo.  The `no-unused-variable` and `prefer-const` rules are very noisy in development if you comment out something temporarily. Both of these issues usually crop up during debugging when you comment out the only call of a function or the only time a variable is reassigned. The `no-console` rule should be obvious :)

More lenient linting during development.

---

Jenkinsfile

I believe the root cause of our recent developer.va.gov outage was https://github.com/department-of-veterans-affairs/developer-portal/pull/79. Since the base branch was master, and there was an associated pull request, the webpack build ran with the `PUBLIC_URL` altered for a review deploy _and_ the archive stage ran as well.
This change ensures that those two things can't happen together: 
- either the jenkins job is running on a PR branch and the webpack build will use our review bucket for the PUBLIC_URL or
- the jenkins job is running on the master branch and the archive stage will run

Prevent archive stage from running on PRs

---

src/components/NavBar.tsx
src/containers/ApplyForm.tsx

This PR updates the Support link in the main nav and the /apply page error message to point to https://github.com/department-of-veterans-affairs/vets-api-clients/issues/new/choose instead of `mailto: api@va.gov`. It's creation was based on [this Slack thread](https://lighthouseva.slack.com/archives/CAZF880HW/p1552927119006700).
This would only be short term until a Support page is created as a follow-up step.

Updates the Support link to vets-api-clients New Issue page

---

SitemapBuilderWebpackPlugin.js
src/containers/ApplyForm.tsx
src/content/apiDocs/benefitsOverview.mdx

This PR fixes all legacy `/explore/terms-of-service` links and changes them to `/terms-of-service`.
There is still code that was supposed to auto-redirect, but it wasn't working in `Routes.tsx` (`<Route path="/explore/terms-of-service" render={props1 => <Redirect to="/terms-of-service" />} />`) but I left that alone for now in case it should be fixed instead of deleted.

fixes all terms-of-service links that were still pointing through /explore

---

src/Routes.tsx
src/components/PageContent.tsx

Turns out the router renders all the matching routes, not just the first or most specific one, if you don't have `<Switch>` around them.

Wrap routes in switch

---

config/polyfills.js
package-lock.json
package.json
public/index.html

This fixes two issues with the developer portal when run in IE11. On VA machines IE11 is configured to run *.va.gov in compatibility mode. We don't want to use compatibility mode because it effectively limits us to ES3 like it's 2008. The manifestation of that errors was a `SCRIPT1010` error in the IE console.
Once running in IE11 mode (which provides ES5) we ran into an issue where IE11 doesn't ship a native `Object.values` method. That's slated for the next ES version, so we should feel safe using it. Rather than importing just the specific methods we'll use I've brought in `@babel/polyfill`. I chose that route because it allows us to specify `es2017` in our `tsconfig.json` file without worrying that the code has passed the type checker due to type definitions for a method that we …

Tell IE11 to disable compat mode and bring in polyfills.

---

src/containers/ApplySuccess.tsx

Merging https://github.com/department-of-veterans-affairs/developer-portal/pull/113 introduced a bug where the `/applied` page always displayed fields for `Your VA API OAuth Client ID` and `Your VA API OAuth Client Secret` even if no OAuth APIs were selected. This PR fixes this.

Fix for /applied page from bug introduced in #113

---

src/content/apiDocs/oauthTechnical.mdx

Updates link to the node sample app in our authorization documentation to coincide with department-of-veterans-affairs/vets-api-clients/pull/63. Also adds a missing comma that was causing to weird coloring in a code block.

Update node sample app path in authorization documentation

---

src/apiDefs.ts

https://github.com/department-of-veterans-affairs/vets-contrib/issues/2444
It is confusing looking at the production developer portal and seeing a swagger doc hosted in 'staging'. It is not an option to grab the document from the current environment. The health API swagger doc is not available in dev. The health API is going to be going through changes in the near future, changing from being hosted at /argonaut to /fhir, so spending a lot of time on this now seems wasteful. Simplest solution is to update the hardcoded health api swagger spec to point to production instead of staging. This allows the spec to still be pulled down in all three environments, with the production development portal showing that the document is from production, which is what users expect.

Argonaut swagger pointed to prod instead of staging

---

src/apiDefs/health.ts

Adds the OpenAPI JSON for Community Care to complete [vets-contrib #2057](https://github.com/department-of-veterans-affairs/vets-contrib/issues/2057).

Add Community Care Eligibility OpenAPI spec - #2057

---

src/content/apiDocs/oauthTechnical.mdx

Updated the link at the bottom of the OAuth authentication documentation to point to the node sample app instead of the test user accounts.

Fix link to node sample app

---

scripts/upload_source_map.sh

https://github.com/department-of-veterans-affairs/vets-contrib/issues/1762
Sentry needs the path to the source map file, https://docs.sentry.io/platforms/javascript/sourcemaps/#verify-artifact-names-match-sourcemappingurl-value.

Set url prefix when uploading source maps

---

src/content/releaseNotes/facilities.mdx

This adds a new release note to the dev portal for a change to the Facilities API `/nearby` endpoint input params

Add Facilities API release note

---

src/components/NavBar.tsx

Got rid of an `em` (not sure why it was there) and a `strong` that was just being used to make something bold.

Remove underline/italics from logo

---

src/containers/Home.tsx

This link is broken on the homepage of the new developer portal. Just a quick fix!

Fix documentation link on homepage

---

src/containers/Home.tsx

Fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/3444
This switches back to a conventional `<a>` tag [in line with this advice](https://github.com/ReactTraining/react-router/issues/1147#issuecomment-98491574), which seems to be the official recommendation.

Fix broken VA.gov link.

---

src/content/apiDocs/oauthTechnical.mdx

This was a regression introduced by me when I reformatted the authorization docs back in March. The `/authorize` name is what is used in a lot of official OAuth and OIDC specification examples but our auth server uses `/authorization`. You can confirm that by looking at either the oauth-proxy source code or the OIDC metadata endpoint: https://dev-api.va.gov/oauth2/.well-known/openid-configuration

Make OAuth examples match real URLs.

---

src/containers/documentation/DocumentationRoot.e2e.ts
src/containers/documentation/DocumentationRoot.tsx

https://github.com/department-of-veterans-affairs/vets-contrib/issues/3704
If the category key in a developer portal URL is unknown the user will be redirected back to the `explore` page. `/explore/invalid` -> `/explore`

Redirect unknown apis to explorer

---

Jenkinsfile
prohibit_image_files.sh

In [another PR](https://github.com/department-of-veterans-affairs/developer-portal/pull/298) I moved the image snapshots over to git-lfs. This adds a CI script to fail PRs that add new images to the relevant directories.

 Add CI script to prevent images being mistakenly added.

---

src/content/apiDocs/verification/verificationReleaseNotes.mdx

This PR addresses [#3658](https://github.com/department-of-veterans-affairs/vets-contrib/issues/3658). It adds a release note for the launch of the Veteran Confirmation API. 
It is targeted against the branch that has a PR to add Veteran Confirmation to the developer portal in #305.

Add release note for Veteran Confirmation API launch

---

src/content/apiDocs/oauthTechnical.mdx

[We fixed a bug in the oauth-proxy](https://github.com/department-of-veterans-affairs/vets-contrib/issues/4015). It was outputting a bogus `expires_at` field that would have been ignored by client applications. It now outputs the standard `expires_in` field, so the docs are being updated to reflect this.

Fix OAuth docs re: expires_in field.

---

src/content/apiDocs/verification/verificationReleaseNotes.mdx

This PR addresses IN-21. It adds a release note for the addition of pay_grade_code and separation_reason for the Veteran Verification API.
The corresponding vets-api PR is https://github.com/department-of-veterans-affairs/vets-api/pull/4016

Add release note for new fields

---

src/apiDefs/data/appeals.ts
src/content/apiDocs/appeals/appealsReleaseNotes.mdx

The current version number has been changed from v3 to v1 (to match vets-api, and not Caseflow)

Fix Appeals Version Number

---

src/content/apiDocs/verification/verificationReleaseNotes.mdx

In order to prevent fraud, consumers of the Veteran Verification API want to verify the Veteran data from VA matches the person applying on USAJobs. To facilitate this, PIV-308 directs the addition of Veteran First & Last name to the service history response.
Feature request.
https://vasdvp.atlassian.net/browse/PIV-308
Corresponding vets-api PR.
https://github.com/department-of-veterans-affairs/vets-api/pull/4121

Added release note for Veteran Verification API

---

src/apiDefs/data/facilities.ts
src/apiDefs/query.test.ts

This PR addresses [API-196](https://vajira.max.gov/browse/API-196). It removes the version selector from the Facilities API since only one version is currently available.

Update facilities documentation to not show version selector

---

src/actions/index.ts

This PR supports [API-180](https://vajira.max.gov/browse/API-180). It points the developer portal apply page at the new developer-portal-backend, which is exposed through the gateway at `/internal/developer-portal-backend`.
The new backend lives in the repo: https://github.com/department-of-veterans-affairs/developer-portal-backend/
Changes to expose it through the gateway happened here: https://github.com/department-of-veterans-affairs/devops/pull/6815

Change URL for apply to new developer-portal-backend

---

src/store.test.ts

Added tests for the store to verify that the apply page is only using cached sessionStorage data when appropriate. As the function `loadApplicationState` is not exported I chose to dynamically import the store in each test to reinitialize it after loading the appropriate value into sessionStorage.

Add tests of cached application state

---

src/containers/Home.tsx
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-3-snap.png

This PR updates the language in the banner warning for consumers needing to migrate from dev to sandbox now that the cutover has happened.

Update sandbox migration banner

---

src/content/apiDocs/verification/verificationReleaseNotes.mdx

Added Veteran Verification API release note to document the new `combined_disability_rating` field and movement of top level ratings into an `individual_ratings` array for clarity to consumers.

Added Veteran Verification release note for combined disability rating

---

src/containers/Home.tsx
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-3-snap.png

Now that consumers have been removed from dev-api.va.gov for two weeks we are removing the banner reminding consumers to migrate to sandbox-api.va.gov. For https://vajira.max.gov/browse/API-890,

Removing sandbox migration banner

---

src/components/Header.tsx
src/components/NavBar.scss

completes [API-937](https://vajira.max.gov/browse/API-937).
allows the mobile menu, which also appears on desktop for zoomed-in screens, to scroll when the screen is zoomed in at 400% or greater to comply with WCAG standards. 
* WCAG 2.1 [Success Criterion 1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) requires that the content be presented in such a way that the user can zoom in at 400% or greater without loss of content and without requiring scrolling in two dimensions. technically, the standard requires these conditions be met for a viewport equivalent to a width of 320 CSS pixels and a height of CSS pixels - in other words, a viewport that is 1280 pixels wide and 1024 pixels high at 100% zoom zoomed in to 400%.
screenshot of the problem before fix:
also …

Allow mobile nav menu to scroll for zoomed-in screens

---

CODEOWNERS

This PR sets up Interrobang as codeowners for the developer-portal repository with one exception: everyone in `lighthouse-apis` would own the `src/content` directory where release notes, news, and documentation live.
This configuration will create noise for members of `lighthouse-apis`, many of who will not care about documentation changes. If we want everyone to be able to approve their own documentation PRs until UX takes over review in the future, this is the only way. Codeowners does not currently support a negation syntax where we could exclude requiring Interrobang for review of `src/content`. 
Alternatively, Interrobang could serve as codeowners of the entire repository and rubberstamp the currently infrequent documentation changes.

Add proposed codeowners

---

src/containers/support/SupportContactUsForm.tsx

This PR supports [API-178](https://vajira.max.gov/browse/API-178). It cuts over the developer portal to use the support email implementation in the `developer-portal-backend` [created in this PR](https://github.com/department-of-veterans-affairs/developer-portal-backend/pull/52). The new route it's sending to is [configured here in devops](https://github.com/department-of-veterans-affairs/devops/blob/e0e7c47636bd8b4c858f7a76d67ca7eb251e1282/lighthouse/gateway/kong_configs/prod_kong.yml#L1646).

Cutover support email to developer-portal-backend implementation

---

docs/issues.md
src/containers/documentation/QuickstartPage.tsx
src/containers/releaseNotes/CategoryReleaseNotesPage.tsx
src/containers/releaseNotes/ReleaseNotesOverview.tsx

completes [API-1329](https://vajira.max.gov/browse/API-1329).
i documented the `properName` category field in `issues.md` for future reference. hopefully we can get rid of it soon. i also removed it from the Quickstart page because both categories that have a Quickstart have identical `name` and `properName` values.

Tweak release notes header

---

package-lock.json
package.json

This PR supports [API-1322](https://vajira.max.gov/browse/API-1322). It removes the `gh-pages` package, which was used in the past when the developer-portal was a prototype but is no longer needed for our build process. It also removes vestigial deploy scripts.

Remove gh-pages and associated scripts

---

package-lock.json
package.json

This PR supports [API-1322](https://vajira.max.gov/browse/API-1322). It removes the `@babel/register` package, which is not used as part of our build process, as far as I can tell. `@babel/register` [provides a way to use babel when files are required](https://babeljs.io/docs/en/babel-register), but it itself must first be required, which does not happen anywhere in `developer-portal`. I wouldn't expect it to be needed, since we use babel via the `babel-loader` as part of our webpack build.
This dependency was added as part of #67, so @nfasulo please let me know if I'm missing something and this package should remain.

Remove @babel/register

---

config/webpackDevServer.config.js
public/google42fbb5f81dacc35d.html
public/google6289781a233ec55f.html

This PR removes Jeff Dunn and adds myself as an owner of the Google Search Console for the developer portal. The Google Search Console allows us to look at the searches performed by search.usa.gov through through the search bar on the developer portal. Google verifies ownership by checking an html file that is included in builds of the developer portal. More info on this verification can be found [here](https://support.google.com/webmasters/answer/9008080#html_verification).
Jeff has also added @charleystran and @bastosmichael as owners. Their verifications can be added in the same way.
PR that added Jeff: https://github.com/department-of-veterans-affairs/developer-portal/pull/71

Change Google Search Console owner

---

Dockerfile

This PR supports [API-2176](https://vajira.max.gov/browse/API-2176). It adds a missing dependency for running headless chrome e2e tests.
Reviewed https://github.com/department-of-veterans-affairs/developer-portal/pull/378 because it was a similar issue and determined that the `libxtst6 ` package needed to be added to the Dockerfile for chrome (to run e2e tests in headless mode).

Add libxtst6 to docker file dependencies.

---

.github/CODEOWNERS

We have split Interrobang into Quokka (provider team) and Okapi (consumer team). Both of these teams still have a vested interest in the developer-portal repo. For now, @charleystran and I want both teams to be co-equal approvers of any PR—only one approval from either team is required to make a PR ready for merging. We may choose to assign more specific ownership in the future.
All are N/A for this change.

Replace Interrobang with Okapi and Quokka

---

package-lock.json
package.json
src/styles/swagger.scss

upgrades `swagger-ui` to 3.31.1 and `msw` to 0.21.2 in order to remediate the low severity `node-fetch` vulnerability that raised a Dependabot alert. part of [API-2578](https://vajira.max.gov/browse/API-2578). 
note that it was _not_ possible to entirely resolve the alert, because `swagger-ui` depends on React 15, which depends on `node-fetch` 1.7.3.
i upgraded `swagger-ui` to 3.31.1 instead of the latest version because at a certain point they screwed something up that caused the UI to render an empty link. the commit is [here](https://github.com/swagger-api/swagger-ui/commit/d9f5691f657dc64842b892255fe4a67cb6246f1b#diff-79a71326f6eb6a6ada641d99a59cd3b5R151). changing the conditional from `externalDocsUrl` to `externalDocs` turns out to be wrong because the `externalDocs` object is …

Upgrade msw to 0.21.2 and swagger-ui to 3.31.1 to remediate node-fetch vulnerability

---

src/apiDefs/data/health.ts
src/content/gettingStarted.mdx
src/content/homePage.mdx

completes [API-1626](https://vajira.max.gov/browse/API-1626) by moving the DSTU2 tab ahead of the R4 tab on the FHIR documentation page. also deleted a couple of old stub Markdown files.
- [n/a] Tests added or updated for change
- [n/a] Accessibility concerns have been considered and addressed

Move DSTU2 tab ahead of R4 tab on FHIR documentation page

---

package-lock.json
package.json
src/base.accessibility.ts

Upgrades Typescript from 3.9.7 to 4.0.3 which is the latest stable release. There is 4.1 in beta currently but stuck with the stable release for all the good reasons.

API-2349/update-typescript-to-v4

---

src/components/pageContent/PageContent.tsx

Jira Ticket: https://vajira.max.gov/browse/API-2909
PageContent should now be using a location hook instead of receiving it as a prop.
- [N/A] Tests added or updated for change
- [N/A] Docs updated
- [N/A] Accessibility concerns have been considered and addressed
Nothing specific

API-2909: Use route hooks on PageContent

---

src/containers/documentation/QuickstartPage.tsx

Jira Ticket: https://vajira.max.gov/browse/API-2911
QuickStart page should now be using a param hook instead of receiving it as a prop.
- [ n/a ] Tests added or updated for change
- [ n/a ] Docs updated
- [ n/a ] Accessibility concerns have been considered and addressed
All feedback is welcome

API 2911: Update QuickStart page to use Route hooks

---

src/containers/documentation/QuickstartPage.tsx
src/containers/releaseNotes/CategoryReleaseNotes.tsx

Jira Ticket: https://vajira.max.gov/browse/API-2912
Category Release Notes pages should now be using a param hook instead of receiving it as a prop.
- [ n/a ] Tests added or updated for change
- [ n/a ] Docs updated
- [ n/a ] Accessibility concerns have been considered and addressed
I have a feeling there might be a useLocation use but couldn't 100% nail down if one was needed.

API 2912:  Update Category Release Notes to use Route Hooks

---

src/containers/documentation/swaggerPlugins/CurlForm.tsx

fixing a bug in the `CurlForm`. https://lighthouseva.slack.com/archives/CDNA4T352/p1605024572060900
- ran `CurlForm.test.tsx`
- part of the problem is that the `CurlForm` unit tests are disabled temporarily because they are very cost-intensive right now. need to refactor to be much more efficient, will create/flag this ticket after this PR gets merged.
- [n/a] Accessibility concerns have been considered and addressed
- bug would definitely qualify as an accessibility issue, fixed

Fix bug in CurlForm from treating shallow-merged React state as if it were deep-merged

---

src/App.tsx

when we uninstalled `connected-react-router`, we accidentally introduced a bug in the Apply flow. for some reason, using separate history objects [within `BrowserRouter`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/BrowserRouter.js#L11) and in our app means that the site routing doesn't respond to programmatic changes from our history object. to fix this issue, we need to use `Router` and pass our history object as a prop: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/BrowserRouter.js#L30
going to deploy as soon as this gets merged.
- [n/a] Tests added or updated for change
- we need integration tests for this, may try to add some but also need to get this change deployed
- …

Use Router instead of BrowserRouter so that React Router uses our custom history

---

src/components/authorizationCard/AuthorizationCard.test.tsx

This adds a test for the AuthorizationCard component.
Jira Ticket: https://vajira.max.gov/browse/API-3756
There were discussions about enabling the imported extend-expect to be available in all of our tests without needing imports on the individual files. That being a decision requiring input and buy in from other teams, I created another Jira ticket for us to cover it (https://vajira.max.gov/browse/API-3947). Note that I do have it working in my local, but I wanted to separate the two PRs.
- [N/A Docs updated
- [N/A] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
- [N/A] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component …

Add initial tests for AuthorizationCard

---

src/containers/support/SupportContactUsForm.test.tsx
src/containers/support/SupportContactUsForm.tsx

Fetch logic migrated to use the wrapper. This component no longer needs to handle integration with Sentry.
- [N/A] Docs updated
- [N/A] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
- [N/A] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [N/A] Accessibility concerns have been considered and addressed
- [N/A] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

API-3736/support contact us form fetch migration

---

src/containers/apply/ApplyForm.test.tsx
src/containers/apply/ApplyHeader.test.tsx
src/containers/apply/DeveloperInfo.test.tsx
src/containers/apply/OAuthAppInfo.test.tsx
src/containers/apply/SelectedApis.test.tsx

This PR is for [API-3529](https://vajira.max.gov/browse/API-3529); it adds testing for the ApplyForm and it's associated components (aside from ApplySuccess, which will be covered in a separate ticket).
Any feedback welcome

API-3529 - Test ApplyForm and related components

---

src/components/header/Header.tsx
src/components/sideNav/SideNav.tsx

The primary and secondary skip nav items don't respect query strings as is. This resolves that issue. Was found during the new auth docs development but is an issue on the API pages currently.

Update Skip Nav links to respect query params

---

Jenkinsfile
cicd/README.md
cicd/buildspec-ci.yml
cicd/buildspec-deploy.yml
cicd/buildspec-release.yml
package.json

does a few things in support of [API-3139](https://vajira.max.gov/browse/API-3139) to make CodeBuild control the main release and production deploy:
- removes the `cb-` prefix from the S3 key used in the CodeBuild archive command.
- also adds a `jenkins-` prefix to the corresponding key in the Jenkins archive command. (worth keeping temporarily, or should we get rid of the Jenkins archive stage entirely?)
- removes the `cb-` prefix from the CodeBuild release tag.
- changes the CodeBuild deploy that's kicked off from the release job to use the release and not the archived commit as the deployment artifacts.
see https://github.com/department-of-veterans-affairs/devops/pull/8446 for changes to Jenkins release + deploy. at the moment, we're only commenting them out.
note that production …

Cut over main release and production deploy to CodeBuild

---

src/apiDefs/data/benefits.ts

This PR supports [API-4350](https://vajira.max.gov/browse/API-4350). It changes the documentation route for the Claims Attributes API from pulling straight from the provider to using the Docserver.
All checks N/A

Change route for Claims Attributes API to Docserver

---

.github/dependabot.yml

Current dependabot configuration is set to ignore version updates from postcss-loader from 4.2.0 to 5.0.0. Correct versions are 3.0.0 to 3.0.0+.
Currently we are getting dependabot version alerts that are blocked.

API-5390: Fix postcss-loader blocked version in dependabot version config

---

src/containers/News.test.tsx
src/containers/News.tsx

Jira ticket [here](https://vajira.max.gov/browse/API-4399)
The page anchor for the Overview tab in the side nav was aiming at the page url instead of a targeted id. I grabbed the id associated with the top of the page and plugged it into the anchor method. 
Had to change the test to check for the anchor url
- [ x] Tests added or updated for change
- [ x] Accessibility concerns have been considered and addressed
Feedback is always nice

API-4399: 'Overview' Button on News Page Doesn't Work

---

src/containers/documentation/swaggerPlugins/CurlForm.tsx

Story: [API-5513](https://vajira.max.gov/browse/API-5513#main)
Duplicate input ids in the curlforms preventing assistive technologies from accurately associating the inputs with labels.
- added aria-label to curlForm input
- tested with NVDA and Narrator
- passes aXe check

API-5513 - CurlForm parameter inputs 

---

src/containers/documentation/swaggerPlugins/StyleOverride.scss

https://vajira.max.gov/browse/API-5944
Pages with html tables that are generated through their swagger docs were having their css collide with the tables within each endpoint's details accordion.
Confirm that the tables on these pages are displaying properly while those on the [auth docs](https://developer.va.gov/explore/authorization?api=claims) aren't affected.
https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current
https://developer.va.gov/explore/benefits/docs/claims?version=current
There shouldn't be any visual regressions failures because these 2 urls are not included in our limited testing set of swagger based pages. Do we want to add one of these to make sure they don't get adversely affected in a future push?

API-5944 - Fix table css on pages with Swagger-UI documentation

---

src/content/apiDocs/benefits/claimsReleaseNotes.mdx

Updates Release Notes to indicate that the ClaimsApi "schema" and "validate" endpoints are being deprecated.
[API-5094](https://vajira.max.gov/browse/API-5904)

[API-5904] - Update Release Notes for ClaimsApi Endpoint Deprecations

---

src/apiDefs/deprecated.test.ts
src/apiDefs/deprecated.ts

[API-2101](https://vajira.max.gov/browse/API-2101)
Adds in the option to set environment variables to overwrite deprecation and deactivation dates. This can be used to test deactivation or deprecation notifications in any environment by setting the env variable. It does still require that the deactivation or deprecation information (dates and content) be set.
The environment variables are in the form `REACT_APP_{key}_DEACTIVATED` and `REACT_APP_{key}_DEACTIVATED` where `{key}` is the api url fragment in all uppercase. (e.g `REACT_APP_CLAIMS_ATTRIBUTES_DEACTIVATED`)

Add env variable option for overwriting deactivation and deprecation dates

---

package-lock.json
src/Routes.tsx
src/components/header/Header.tsx
src/components/navBar/NavBar.tsx
src/containers/Home.tsx
src/containers/documentation/ApiDocumentation.tsx
src/containers/documentation/ApiPage.tsx
src/containers/documentation/CategoryPage.tsx
src/containers/documentation/DocumentationOverview.tsx
src/containers/documentation/DocumentationRoot.tsx
src/containers/releaseNotes/CategoryReleaseNotes.tsx
src/containers/releaseNotes/ReleaseNotes.tsx
src/containers/releaseNotes/ReleaseNotesOverview.tsx
src/types/constants/index.ts

https://vajira.max.gov/browse/API-4018
The goal here is to move all flag names to use constant values to make any future refactoring much easier and prevent accidental changes that break existing flags.

API-4018: Move flag names to constants

---

src/content/apiDocs/benefits/claimsReleaseNotes.mdx

Adds a release note to ensure consumers are made aware of a change in our documentation to reflect the current implementation around 2122 submission.
Requires the PR making this change to be deployed next Monday:
https://github.com/department-of-veterans-affairs/vets-api/pull/6728
otherwise the date defined in this pr will need to change

API-6498: Release note for Limited Consent Schema correction

---

Makefile
package-lock.json
package.json

This is a shortcut fix that skips past the larger fixes going on in #731. The immediate goal is to allow builds to pass again and clear out a backlog of pending and approved PRs since this fix is an incremental improvement to what's currently released by fixing all the high vulnerability items and half of the moderate items.
https://vajira.max.gov/browse/API-7014

API-7014: Check for high vulnerability packages to restore builds

---

src/apiDefs/data/benefits.ts

[API-7143](https://vajira.max.gov/browse/API-7143)
Update docs path so they aren't blocked by adblock causing the whole doc page to fail
`oas.js` is filtered by some adblockers and we named our OAS files `oas.json` which got blocked. The file is now named `openapi.json`.

API-7143 Update doc path for claims-attributes

---

README.md

Update readme instructions for adding a new API to the apply page. Since formik was added, we no longer have the reducers and actions that were mentioned previously. Also called out that the backend will also need to be updated and updated references to the old `developer-portal-lambda-backend`

Update instructions for adding an API to apply page

---

package-lock.json
package.json

Updates `dns-packet` to resolve a vulnerability and allow builds to continue.

Resolve dns-packet to 5.2.2 due to npm audit alert

---

src/containers/support/ContactUsForm/ContactUsForm.test.tsx
src/containers/support/ContactUsForm/ContactUsForm.tsx
src/types/contactUsForm.ts

This fixes an integration issue between the form and the backend. If the internal only radio button was set to No, the front end would still send whatever it had for the internal only details.

Don't send internal only details when api is not internal only

---

cicd/buildspec-deploy.yml
cicd/buildspec-review-deploy.yml

https://vajira.max.gov/browse/API-7870
This will create a new file at `/deploy.json` that includes current hash, environment, date of deploy and release version in each environment.
Wait for the deploy job to finish and check for the file.

API-7870 - Create build.json on deploy with build specs

---

src/apiDefs/data/verification.ts

[API-7959](https://vajira.max.gov/browse/API-7959)
The metadata url is used to define the need for a seperate version display. Address Validation now has multiple versions and a need for the metadata url. Quokka has deemed it prudent to claim ownership of the metadata because we are modifying each OAS that is served to have relevant pathing, servers, and security. Since we have knowledge of each API and their versions, it makes sense for the Docserver to generate such metadata. This is a manual attempt to prove out the concept.

API-7959 Update Address Validation metadata url to S3

---

src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
src/containers/documentation/swaggerPlugins/CurlForm.tsx
src/containers/documentation/swaggerPlugins/VersionSelector.test.ts
src/containers/documentation/swaggerPlugins/VersionSelector.ts
src/types/swagger-client.d.ts

[API-7950](https://vajira.max.gov/browse/API-7950)
Change logic of the cURL form generator to use the metadata url or fallback to OAS as a default

Api 7950/change curl to use oas

---

Dockerfile

https://vajira.max.gov/browse/API-8095
Simply change a COPY command's default file ownership to avoid needing to become root.

Remove root from DockerFile for Fortify Scan

---

jest-puppeteer.config.js
src/containers/consumerOnboarding/ConsumerOnboardingRoot.tsx
src/containers/consumerOnboarding/DemoPrep.scss
src/containers/consumerOnboarding/DemoPrep.test.tsx
src/containers/consumerOnboarding/DemoPrep.tsx
src/containers/consumerOnboarding/OnboardingOverview.test.tsx
src/containers/consumerOnboarding/OnboardingOverview.tsx
src/e2eHelpers.ts
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-prepare-for-and-complete-a-demo-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-prepare-for-and-complete-a-demo-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-prepare-for-and-complete-a-demo-properly-3-snap.png

adds "prepare for a demo" page to consumer docs. completes [API-7690](https://vajira.max.gov/browse/API-7690).
- [design](https://www.figma.com/file/9sOD2GDAsyNTayvOqKlcJV/API-3854-Consumer?node-id=1397%3A840)
- [content](https://docs.google.com/document/d/1Q-uzP4nEz56tyFnprteMwzgaKi9BhqZHg_iqlkAn-Nw/edit)
- [n/a] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated

Create demo preparation page in consumer onboarding docs

---

src/components/oauthDocs/AuthCodeFlowContent.mdx
src/components/oauthDocs/PKCEAuthContent.mdx

Remove `state` from calls to `/token` as it's not required nor used.
https://vajira.max.gov/browse/API-7851

API-7851 - Remove state from token requests

---

src/apiDefs/data/benefits.ts

Disables the display of `Claims Attributes` API documentation in preparation for the APIs upcoming deprecation.

[API-8109] - Disable the display of Claims Attributes API documentation

---

src/containers/support/ContactUsForm/ContactUsForm.test.tsx
src/containers/support/ContactUsForm/ContactUsForm.tsx

This adds an alert box to the contact form if there is an error encountered while communicating with the server. This is setup to match what the apply page does currently.

Add server error message

---

.github/CODEOWNERS

Add team marmoset to the codeowners for any jira tickets they'll need to do

Add team marmoset to codeowners

---

src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.test.tsx
src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.tsx

This PR is for [API-8734](https://vajira.max.gov/browse/API-8734). Currently the `handleSubmit` function that creates an application in Okta, etc. is getting called twice. Removing the implicit `submitForm()` call makes it so the function is only called once.
Do I have prettier misconfigured? I noticed that I have a lot of formatting changes in the `SandboxAccessForm.tsx` file

Remove implicit submitForm call from apply form

---

src/components/oauthDocs/AuthCodeFlowContent.mdx
src/components/oauthDocs/AuthCodeFlowContent.tsx
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-properly-3-snap.png

Clarify the use of base64 to encode client_id and client_secret.
It should be clear that `client_id:client_secret` should be base64 encoded as a whole. Previous interpertation was that base64 only applied to `client_id`.

Clarify the use of base64 to encode client_id and client_secret

---

src/containers/documentation/swaggerPlugins/StyleOverride.scss

This is removing the `display:none` in the styles override because that is disabling the parameter examples in the cURL generator which removes a significant portion of the documentation for no discernible gain that I can see.
Please let me know if you see any other impacts.

API-8750 Fix curl parameter examples

---

package-lock.json
package.json

https://vajira.max.gov/browse/API-6992
While this was intended to update USWDS to v2 there are existing [compatibility issues](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/issues/625) that exist in Formation that prevent the upgrade to USWDS v2 so this ticket now just handles the updates to the latest minor versions.

Update USWDS to latest v1 release

---

src/apiDefs/data/benefits.ts

This PR is for [API-9811](https://vajira.max.gov/browse/API-9811) - it updates the Benefits Intake API description so that documentation will be fetched according to the metadata JSON provided by Docserver.

Add metadata url to Benefits Intake API

---

cicd/buildspec-ci.yml

When CI jobs fail outside of the test a notification is sent to Slack to see if there is a problem with CodeBuild. These notifications were using the wrong webhook and being sent to DSVA workspace. 
This PR also updates the message with codebuild ID for easier identification.

Update CI failure slackwebhook

---

src/containers/consumerOnboarding/components/sandbox/InternalOnlyInfo.tsx

Story: [API-10386](https://vajira.max.gov/browse/API-10386)
Remove the sentence "Provisional access takes 2-3 business days." from the Address Validation section of the Request Sandbox Access page.

API-10386/Remove provisional access copy from address validation

---

.github/workflows/new-release.yml

https://vajira.max.gov/browse/API-9848
Checkout needs to include the ref of the latest release to make a new one

API-9848 - Grab latest release to set new release tag

---

.github/workflows/new-release.yml

https://vajira.max.gov/browse/API-9848
This is the last of the steps required to generate releases from GitHub Actions. At this time the webhook that triggers `developer-portal-ci` is disabled so as to not double up on releases (like v0.0.778 and v0.0.779 intentionally did). Triggering the actual deploys of the packaged files still runs from `developer-portal-deplpoy` so no changes to the dev, staging, and production deploys are needed.
Should be ever return to automated deployments, either daily or perhaps on merge to master, that would need to be updated.

API-9848 - Change from CodeBuild releases to GitHub Actions

---

src/components/formField/FieldSet/FieldSet.test.tsx
src/components/formField/FieldSet/FieldSet.tsx
src/containers/consumerOnboarding/components/productionAccessForm/BasicInformation.tsx

This PR adds a description to the "Is your application Veteran-facing?" question in the prod access request form.
[API-11439 - Visual and Screen Reader Indication of Hidden, Conditional Fields](https://vajira.max.gov/browse/API-11439)

API-11439 Add a description to a prod access question

---

src/apiDefs/data/benefits.ts
src/apiDefs/query.test.ts
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-client-credentials-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-client-credentials-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-client-credentials-properly-3-snap.png

Removed invalid scopes from Claims CCG docs. Since Client Credentials Grant flow does not have an attended user, openid, profile, and offline_access are not applicable.

Api 12694 fix scopes for benefits claims ccg flow

---

src/apiDefs/query.ts

This change ensures the list of APIs on the production apply page is sorted alphabetically (as it is on the sandbox apply page).

sorts all apis list on the production apply page

---

.github/workflows/auto-deploy-to-production.yml
.github/workflows/create-auto-deploy-maintenance-request.yml

https://vajira.max.gov/browse/API-12829
Changed from GITHUB_SECRET token which only has access to this repo to a PAT token which gives access to org repos including lighthouse-devops-support which is needed for this.

[API-12829] - Update token to allow cross repo access

---

.github/workflows/auto-deploy-to-production.yml

https://vajira.max.gov/browse/API-3913
Because there's no checkout we need to tell `gh run cancel` which repo to cancel the run on.

[API-3913] - Fix run cancel with specific repo

---

src/components/oauthDocs/acg/GettingStarted.tsx
src/components/oauthDocs/ccg/GettingStarted.tsx

Came across these typos during a spike on prerendering pages (API-3913) and just doing a quick PR to resolve them. I did a quick audit of all the mailto: links across the dev portal and should be good to go after this is merged.

Fix small but impactful typos in mailto: links

---

.github/workflows/auto-deploy-to-production.yml
.github/workflows/create-auto-deploy-maintenance-request.yml

https://vajira.max.gov/browse/API-13873
This PR fixes an issue where the MR creation wouldn't check to see that the proposed release version wasn't already out on production.
Other quality of life improvements:
- Jobs will no longer self-cancel when there's a condition that would stop an MR creation or auto deploy.
- This will stop the jobs from sending GitHub notifications of a cancelled job even when only alert for failures if set.
- The auto deploy job will now only run it's scheduled tasks after an MR is created.
- Upon successful creation of an MR `gh workflow enable 'Auto Deploy master to Production'` will run to enable the schedule to run every half hour
- Upon successful deploy to production `gh workflow disable 'Auto Deploy master to Production'` will run to disable the schedule …

[API-13873] - Fixes to MR creation script

---

.github/workflows/pr-requires-label.yml

https://vajira.max.gov/browse/API-13935
The auto maintenance request creation process (as part of the developer-portal's auto deploy pipeline) requires that all merged PRs include a label so they can be marked as having an impact on the user or on the maintainer.

[API-13935] - Add label requirement to PRs

---

.github/workflows/auto-deploy-to-production.yml

https://vajira.max.gov/browse/API-13873
GitHub Actions has to queue jobs to run at times and previously the auto deploy would support up to a 9 minute delayed start. This changes allows for up to a 19 minute delayed start as there have been a couple instances where 9 just wasn't enough time.

[API-13873] - Allow for longer queued deploy jobs

---

src/containers/documentation/swaggerPlugins/CurlForm.tsx

https://vajira.max.gov/browse/API-14211
An unexpected change to `.security.OauthFlow` and `.components.securitySchemas.OauthFlow` caused the bearer token to now be reflected in the curl generator form. This accounts for new options that pass that information from the open API specs.

[API-14211] - Fix bearer token on CurlForm

---

src/containers/publishing/components/publishingOnboarding/PublishingOnboarding.tsx

https://vajira.max.gov/browse/API-14306
External link was using `<Link to=` as opposed to using `<a href=` as it should be. Also confirmed no other instances of `to="http` exist in the codebase which would indicate other similar issues.

[API-14306] - Fix broken link

---

src/containers/consumerOnboarding/ProductionAccess.tsx

https://vajira.max.gov/browse/API-10046
The cancel button on the Production Access Form would have some odd behaviors in some scenarios like direct links from external sites and bookmarked links. This provides a uniform path for all users when they click cancel.

[API-10046] - Consumer docs leave button flow update

---

.github/workflows/auto-label-content-prs.yml

https://github.com/actions/labeler/issues/104
Implement a workaround for a bug in `actions/labeler@v3` so that labels added before a PR is created will no longer get erroneously removed.

Workaround for labeler action bug

---

src/containers/documentation/swaggerPlugins/CurlForm.tsx

https://vajira.max.gov/browse/API-14744
Fixes Veteran Verification APIs that use http auth with bearer tokens as #1006 broke that.

[API-14744] - Fix support for http auth / bearer_token endpoints

---

.github/workflows/auto-deploy-to-production.yml

https://vajira.max.gov/browse/API-15130
department-of-veterans-affairs/lighthouse-devops-support#1324
My assumption here is that while the actual building process is done and the status field is marked as "completed" there are still cleanup process that are running which means that the final end hasn't been hit yet. That would cause the `.builds[0].endTime` to be unset while simultaneously allowing for `.builds[0].currentPhase` to be set to "COMPLETED"
Unfortunately there is no way to truly test this hypothesis and we can only know if this is actually the case if / when there's an error with a future build that trips up this seemingly edge case scenario.

[API-15130] - Gracefully allow for endTime to not yet be set

---

cypress.json
cypress/integration/faqs.spec.js
cypress/integration/page-content.spec.js
package-lock.json
src/components/pageContent/PageContent.tsx

https://vajira.max.gov/browse/API-14968
A previous bug in [API-9003](https://vajira.max.gov/browse/API-9033) caused the need to make focus and scroll separate events, this PR blocks the additional scrolling that's triggered by `.focus()` when page navigation doesn't require jumping to a specific anchor isn't called for.

[API-14968] - Content flash / scroll on navigation

---

src/containers/consumerOnboarding/ProductionAccess.tsx
src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.tsx
src/containers/support/ContactUsForm/ContactUsForm.tsx

I think this will fix the current issue in dev with the developer-portal talking to LCMS. (LCMS not being able to access the cookie generated and stored by the developer-portal)
It seems that the default "SameSite" value is `None` and if that is set and "Secure" isn't set, the cookie is "blocked"?
Strict should be what we want anyways. Should restrict it's usage to the specific dev-developer.va.gov domain.

set cookie SameSite value to Strict

---

src/content/apiDocs/appeals/decisionReviewReleaseNotes.mdx

Consumers want to enable non-Veteran Claimants to submit HLRs and need to be aware of additions, deprecations, and changes to the relevant endpoints.
Details
Publish the Release Notes describing the new Non-Veteran Claimant functionality for HLR.  Darcy has approved the following:
On MONTH DD, YYYY, we added functionality to our Higher-Level Review (HLR) POST endpoint to support submissions by non-Veteran claimants. This allows HLRs to be submitted by dependents of a Veteran.
To learn more, read the [Decision Reviews API documentation](https://dev-developer.va.gov/explore/appeals/docs/decision_reviews?version=current).
[API-14885](https://vajira.max.gov/browse/API-14885)

API-14885 release notes for HLR NVC.

---

.github/workflows/pr-builds-privileged.yml

https://vajira.max.gov/browse/API-13962
The deploy file is `deploy.json` not `build.json`. This fixes that so the build can proceed.

[API-13962] - Fix PR fetch from deploy.json file

---

.github/workflows/visual-regressions-privileged.yml
.github/workflows/visual-regressions-unprivileged.yml

https://vajira.max.gov/browse/API-13962
Update the privileged visual regressions workflow to grab the branch name from the artifact storage like we do for pr number and hash.

[API-13962] - Get visual regression branch from artifact storage

---

.github/workflows/visual-regressions-privileged.yml

https://vajira.max.gov/browse/API-13962
Doing a second checkout won't just change the branch like I'd hoped. We need to re-download the artifacts from the previous run.

[API-13962] - Re-download artifacts during visual regressions

---

src/apiDefs/data/verification.ts
src/apiDefs/query.test.ts
src/containers/consumerOnboarding/RequestProductionAccess.tsx

https://vajira.max.gov/browse/API-15828
No longer require privacy policy and terms of service information to be submitted with Veteran Confirmation production access requests. Still requires those fields when there's another oAuth API selected on a form submission.

[API-15828] - Omit page 4 from Vet Confirmation prod access form

---

src/apiDefs/data/health.ts

Correct Clinical Health API Auth Base Path to V2 with the upgrade to SSOi OAuth.

API-000 Correct CHAPI Auth Base Path

---

src/content/apiDocs/appeals/decisionReviewReleaseNotes.mdx

Adds deprecation notice for HLR V1.
[Ticket: API-16011](https://vajira.max.gov/browse/API-16011)
[Vets API PR](https://github.com/department-of-veterans-affairs/vets-api/pull/10063)

API-16011 Adds deprecation notice for HLR V1

---

src/types/constants/index.ts

LGY Guaranty Remittance is currently not showing the sandbox apply form success page ccg client id from the response.
This fixes that issue.

show lgy guaranty remittance on success page

---

src/components/formField/TextField/TextField.tsx
src/containers/consumerOnboarding/components/sandbox/OAuthAcgAppInfo.tsx
src/containers/consumerOnboarding/components/sandbox/OAuthCcgAppInfo.tsx
src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.tsx

Displays error message from backend response in environments other than development.
Switches CCG public key field to a textarea.
Adds placeholder example text for both CCG public key field and ACG redirect uri field (to help reduce confusion)

API-16786: Improve error handling when registering for CCG credentials

---

src/containers/documentation/swaggerPlugins/VersionSelector.test.ts
src/containers/documentation/swaggerPlugins/VersionSelector.ts

https://vajira.max.gov/browse/API-17136
The prefixed api versions found in the dropdown for Patient Health API caused issues with the curlform generator because it was simply taking the first character rather than the actual major version. An oversight from #1065.
The Patient Health API versions come in `[API]-[version]` format (ex. `r4-0.0.0`) while the other APIs that are just one true API just have the version number.

[API-17136] - Adjust majorVersion to support prefixed versions

---

src/components/formField/FieldSet/FieldSet.tsx

https://vajira.max.gov/browse/API-16650
Change formatting of secondary text "If yes, we will ask for more details" in production request form to match other similar elements in the form.

API-16650: Secondary Text Not Using Correct Styling Rules in Prod Access Form

---

.env.production

Health Quick Start documentation mentions several urls that currently point to production. The documentation around them talks about developing in sandbox. This code change changes the urls [here](https://developer.va.gov/explore/health/docs/quickstart) to point to sandbox.
I scoured the project to make sure this environment variable isn't being used anywhere else. I only found it used in this one document, so I think we should be safe to change it.
Additional info: this is the PR where this environment variable was introduced:
https://github.com/department-of-veterans-affairs/developer-portal/pull/158

point health doc urls at sandbox instead of production

---

src/apiDefs/data/loanGuaranty.ts
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-request-sandbox-access-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-request-sandbox-access-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-request-sandbox-access-properly-3-snap.png

Flag Guaranty Remittance as "internal only" due to it having restricted access for now.
https://vajira.max.gov/browse/API-18310
All LPB environments have been updated as well.

API-18310: Add Internal Only Label to LGY API in Sandbox Access Form

---

src/containers/releaseNotes/CategoryReleaseNotes.tsx
src/containers/releaseNotes/ReleaseNotes.scss
src/containers/releaseNotes/ReleaseNotes.tsx

https://vajira.max.gov/browse/API-17268
Release notes that have a single line break instead of 2 which triggers a new paragraph with `react-markdown` need this to allow for new lines to appear.

[API-17268] - Add white-space pre-wrap for release notes fix

---

.github/workflows/cypress-smoketest.yml
.gitignore
cypress.json
cypress/integration/smoketest.spec.js
smoketest/Gemfile
smoketest/Gemfile.lock
smoketest/delete-smoketest-apps.rb

https://vajira.max.gov/browse/API-18737
This sets up an hourly smoke test to run against the signup form at https://dev-developer.va.gov/onboarding/request-sandbox-access and, if there is a failure, alerts the team through the `#vaapi-alerts` channel in the Lighthouse Slack workspace. This test kicks off at 20 minutes past the hour, every hour, everyday.

[API-18737] - hourly signup smoke test

---

src/containers/consumerOnboarding/ProductionAccess.tsx
src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.tsx
src/containers/support/ContactUsForm/ContactUsForm.tsx
src/types/constants/index.ts

https://vajira.max.gov/browse/API-20646
The initial WASA scan for the developer portal flagged the use of `Math.random()` as an issue because it is not cryptographically secure. Our use of it is not necessary and can be omitted entirely because we're using `SameSite=String` which coupled with sending the value as both a header and cookie means it cannot be sent maliciously via csrf regardless of the actual contents of the token.

[API-20646] - Change out Math.random() for static forgery token

---

.github/workflows/pr-requires-label.yml

https://vajira.max.gov/browse/API-21166
Updated workflow that positive checks for a label of `impact: users` or `impact: maintainers` to also negative check for a `DO NOT MERGE` label.

[API-21166] - Add merge blocker when PR is labeled DO NOT MERGE

---

src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
src/containers/documentation/swaggerPlugins/CurlForm.tsx

https://vajira.max.gov/browse/API-21322
Provide the proper handling of an array of objects in the Curl Form plugin for Swagger-UI.
See [Higher Level Reviews](https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current) in Decision Reviews API for an example of it not working as expected.

[API-21322] - Add support for array of objects to curl form

---

src/containers/documentation/ApiPage.test.tsx
src/containers/documentation/ApiPage.tsx

This PR updates API pages to display the category veteran redirect message as a fallback when an API specific veteran redirect message doesn't exist.

[API-20045] - Use category veteran redirect message as fallback

---

.github/workflows/codeql.yml

[Original Issue](https://vajira.max.gov/browse/API-22128)
Updates CodeQL GitHub Action to V2.

[API-22128] - Update CodeQL GitHub Action to V2

---

src/containers/documentation/swaggerPlugins/curlify.test.ts
src/containers/documentation/swaggerPlugins/curlify.ts

https://vajira.max.gov/browse/API-22393
Surfaced with Direct Deposit Management, the CurlForm plugin, and more specifically the `curlify.ts` logic under it only supported a `requestBody` for a `POST` request. This updates it to include `PATCH`, and `PUT` methods.

[API-22393] - Update curlify.ts to support PATCH/PUT

---

src/components/oauthDocs/ccg/GeneratingJWTContent.tsx

https://vajira.max.gov/browse/API-22495
So we don't show the `sandboxAud` value on the production okta endpoint, we're hiding the production endpoint when the `sandboxAud` and `productionAud` are matching values.

[API-22495] - Conditionally hide prod aud from ccg auth

---

cicd/buildspec-deploy.yml

Original Issue :: [API-22006](https://vajira.max.gov/browse/API-22006)
Sometime back in March 2022, the Sentry Releases integration stopped working.  The change in this PR attempts to get it working again by adding the `--ignore-missing` flag that is documented [here](https://docs.sentry.io/product/cli/releases/#dealing-with-missing-commits).

[API-22006] - Attempt to fix Sentry Releases integration

---

cicd/buildspec-deploy.yml
scripts/upload_source_map.sh

- Adds logic to try and upload source maps with Sentry Releases
- Removes a script (`scripts/upload_source_map.sh`) that supposedly use to do this through integration with a Jenkinsfile.  But that Jenkinsfile no longer exists and it doesn't appear that anything is referencing the script anymore.
- The original commit where that script was created and referenced by the Jenkinsfile can be found [here](https://github.com/department-of-veterans-affairs/developer-portal/commit/b8c46813dc7bae86710d8de5bd16ce03563674c7).

[API-22006] - Attempt to add source maps to Sentry Releases

---

cicd/buildspec-deploy.yml

Tweaks the Sentry Release upload sourcemap path.
- The Sentry Release command currently looks like this ::
```
sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps build/${env}/static/js --url-prefix '~/static/js'
```
- But, it looks like maybe the file path for the JS assets look like this ::
```
...
upload: production/static/js/1.9e29021b.chunk.js to s3://developer.va.gov/static/js/1.9e29021b.chunk.js
upload: production/static/js/0.c3524841.chunk.js to s3://developer.va.gov/static/js/0.c3524841.chunk.js
upload: production/static/js/0.c3524841.chunk.js.map to s3://developer.va.gov/static/js/0.c3524841.chunk.js.map
....
```
- So I'm changing the arg from `build/${env}/static/js` -> `${env}/static/js`

[API-22006] - Tweak the Sentry sourcemap upload path

---

src/components/header/Header.tsx

https://vajira.max.gov/browse/API-24179
Adds a banner to the Appeals Status API about the future v1 version.

[API-24179] - Add v1 banner to Appeals Status API

---

.github/ISSUE_TEMPLATE/config.yml

- Adds a GitHub issue template config to the repo.  This will allow us to direct contributors to the DevPortal's ["Developer Portal Support"](https://developer.va.gov/support/contact-us) page when creating new issues in the repo.

[API-24155] - Add GH issue template config

---

.github/workflows/cypress-smoketest.yml

https://vajira.max.gov/browse/API-19485
Update to node 18 broke the Cypress smoketest on the sandbox signup form on dev. This resolves that oversight.

[API-19485] - Fix / upgrade cypress smoketest

---

src/containers/consumerOnboarding/validationSchema.ts

Original Issue :: [API-25845](https://vajira.max.gov/browse/API-25845)
- Removes overly strict validation on the `piiStorageMethod` field in the "Production Access Form".  This validator rejects the user input if it contains the word `email`.  It will also reject words such as `test`, `sample`, and `fake`.  Maybe an alternative fix would be to tweak the validator to not look for the word `email`, but that validator is used in a lot of places.  so I tried to make the "fix" as small reaching as possible.

[API-25845] - Fix overly strict form validation of "piiStorageMethod" field

---

src/utils/deprecationBannerHelper.tsx

Original Issue :: [API-27586](https://jira.devops.va.gov/browse/API-27586)
- Reverts the verbiage on the deprecation banner for the Facilities API back to what it was yesterday.

[API-27586] - Revert FacilitiesAPI deprecation banner verbiage

---

src/components/mainNavItem/MainNavItem.tsx
src/components/navBar/NavBar.scss
src/components/navBar/NavBar.tsx

[API-24006 cont.](https://jira.devops.va.gov/browse/API-24006)

[API-24006] Header cont.

---

package-lock.json
package.json
src/containers/documentation/swaggerPlugins/CurlForm.test.tsx
src/containers/documentation/swaggerPlugins/CurlForm.tsx

There was a discrepancy between the posting of the older sandbox-access-form package and what was on dev. This updated package rectifies that discrepancy.
Also included is a small fix to the CurlForm Swagger plugin which updates the link to the Sandbox access form to be correct and API specific.

Fix Sandbox Access form

---

cicd/buildspec-deploy.yml
src/containers/documentation/RequestSandboxAccess.tsx

This resolves the issue where the form was posting the urlFragment and not the altId. Most older APIs have these values matching which caused many false positives.

Resolve sandbox access for mismatching altId and urlFragment

---

.github/workflows/notify-security-alerts.yml

Original Issue :: [API-27988](https://jira.devops.va.gov/browse/API-27988)
- Adds a GitHub Action workflow that checks for any security vulnerability alerts in the repo and sends a Slack notification to the `#team-okapi-alerts` channel if any are found.

[API-27988] - Add GHA workflow for monitoring security alerts

---

src/containers/documentation/swaggerPlugins/VersionSelect.tsx

[API-28414](https://jira.devops.va.gov/browse/API-28414)
This PR fixes displaying the API version banner on version change for all APIs. Previously, the banner was incorrectly only displaying for FHIR API version changes.

[API-28414] Display banner on version select

---

.github/workflows/visual-regressions-privileged.yml

https://oddball.slack.com/archives/C02GF07P3QU/p1691511274010189
Spotted that visual regressions were not posting back to the PRs on this Slack thread. Because of a change to the underlying GHA worker machine, adding sudo should fix the [permissions issue](https://github.com/department-of-veterans-affairs/developer-portal/actions/runs/5798933462/job/15717788506).

Add sudo for apt command

---

.github/workflows/cypress-smoketest.yml
.github/workflows/cypress-tests.yml
.github/workflows/generate-visual-regressions.yml
.github/workflows/new-release.yml
.github/workflows/npm-checks.yml
.github/workflows/pr-builds.yml
.github/workflows/visual-regressions-unprivileged.yml

https://jira.devops.va.gov/browse/API-28055
Remove the webfactort/ssh-agent GitHub workflow action as [sandbox-access-form repo](https://github.com/department-of-veterans-affairs/va-api-sandbox-access-form) is now open sourced so an SSH key is no longer needed to install the package.

[API-28055] - Remove webfactory/ssh-agent

---

src/styles/base.scss

This PR updates the z-index for any modal using the `va-modal` class to display above all other elements.
Origin:

Display all modals on top

---

.github/workflows/cypress-smoketest.yml

https://jira.devops.va.gov/browse/API-29516
Now failing tests will not stop the cleanup steps from running leaving lots of orphaned apps in Okta.

[API-29516] - Patch failure scenario on smoketest

---

cypress/e2e/components/Routes.cy.js
cypress/fixtures/legacy.json
cypress/plugins/getRequiredApiSignups.js
public/data/platform-backend/v0/providers/transformations/legacy.json
src/__mocks__/fakeCategories.tsx
src/apiDefs/deprecated.test.ts
src/apiDefs/env.test.ts
src/apiDefs/query.test.ts
src/apiDefs/schema.ts
src/containers/documentation/ApiDocumentation.test.tsx
src/containers/documentation/ApiOverviewPage.tsx
src/containers/documentation/ApiPage.test.tsx
src/containers/documentation/ApiPage.tsx
src/containers/documentation/DocumentationRoot.tsx
src/containers/documentation/ReleaseNotes.tsx
src/containers/documentation/RequestSandboxAccess.tsx

https://jira.devops.va.gov/browse/API-29775
This will use the `blockSandboxForm` property as the source of truth for whether or not to show the sandbox access form.
Additionally I updated some of the 404 conditionals to use the `throw new Error('API not found')` as a way to limit the number of different places we were calling for the 404 page to have to load in. It will show an error on local but when deployed that error should disappear and users will see the 404 page right away.

[API-29775] - Block sandbox-access route by LPB property

---

.github/workflows/cypress-tests.yml
.github/workflows/npm-checks.yml
.github/workflows/pr-builds.yml
.github/workflows/pr-requires-label.yml

This change will allow for CI tasks to run mostly unchanged against a new, temporary, `shutdown-master` branch. This is only going to be necessary if there is a government shutdown and merges to the `master` are restricted to just critical updates.

[Shutdown Prep] - Prep for a locked master branch

---

package-lock.json
package.json

Original Issue :: [API-30623](https://jira.devops.va.gov/browse/API-30623)
- Updates the `PostCSS` dependency [as directed by Dependabot](https://github.com/department-of-veterans-affairs/developer-portal/security/dependabot/79).

[API-30623] - Update PostCSS dependency to fix Dependabot alert

---

src/containers/documentation/ApiDocumentation.tsx

https://jira.devops.va.gov/browse/API-30849
Removes this check because it's blocking specifically the swagger docs on a stealth launched API from being viewable on the portal.

[API-30849] - Remove Flag around SwaggerDocs

---

package-lock.json
src/apiDefs/schema.ts
src/containers/documentation/DocumentationRoot.tsx
src/containers/documentation/TestUsersPage.test.tsx
src/containers/documentation/TestUsersPage.tsx

https://jira.devops.va.gov/browse/API-34671
Specifically requested for the Clinical Health API but built to be configurable, this will allow us to add `disableTestUsersPage: true` to the `acgInfo` property within LPB to disable an API's Test Users page when they have ACG OAuth available.

[API-34671] - Conditionally disable test users page

---

.github/workflows/pr-requires-label.yml

Small workflow update to resolve issue where visual regressions would not re-trigger this CI test.

Update PR label workflow run trigger
