.gitignore
LICENSE
README.md

Brought over the gitignore file and added a basic readme. Let me know if there's anything I need to add.

Add documentation

---

src/containers/Home.tsx

Fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/606

Update link on homepage for requesting production access

---

package-lock.json

Mostly doing this because github keeps bugging me about the event-stream vuln which was fixed here: https://github.com/department-of-veterans-affairs/developer-site/pull/5 so maybe fixing this other one will help.

Update dependency with a vulnerability

---

src/containers/Explore.tsx

Closes department-of-veterans-affairs/vets-contrib#699
TODO: Remove old fetch code for swagger 2.0
TODO: Change endpoint to be unique for environments

Add new argonaut docs

---

src/content/apiDocs/oauthTechnical.md

Refs https://github.com/department-of-veterans-affairs/vets-contrib/issues/699

Add health oauth scopes to documentation.

---

src/containers/Apply.tsx

Custom message when requesting health APIs

---

src/content/apiDocs/healthOverview.md

Updated health overview to reflect the most recent base URI.

Update Health Overview

---

src/containers/OAuth.scss
src/content/apiDocs/oauthTechnical.md

This fixes the scroll overflow issue noted in https://github.com/department-of-veterans-affairs/vets-contrib/issues/436.
[before_auth_code_flow](https://user-images.githubusercontent.com/45699/49601081-758ef780-f94a-11e8-9cb4-80ef12a6ea5c.png)
[before_init_auth](https://user-images.githubusercontent.com/45699/49601082-76278e00-f94a-11e8-804d-edf9db58ed9b.png)
[after_auth_code_flow](https://user-images.githubusercontent.com/45699/49601070-6e67e980-f94a-11e8-8f25-f8a0fa04a1c4.png)
[after_init_auth](https://user-images.githubusercontent.com/45699/49601071-6e67e980-f94a-11e8-85bd-bb86977050d3.png)

Tweak oauth docs to scroll properly.

---

src/containers/Beta.tsx

@edpaget just changing the UAT org ID!

UAT OId change

---

Jenkinsfile
package-lock.json
package.json
src/containers/Beta.tsx

@edpaget the VICSIT environment IDs all changed, so this just updates them.

updated field IDs and Oid for VICSIT

---

src/containers/Explore.scss
src/containers/Explore.tsx
src/containers/ExploreDocs.tsx

Also makes the API links one per row, they were stacking on each other and ordering weirdly

Add claims documentation

---

Jenkinsfile
src/base.scss

Resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/853
Adds functionality to report results of the visual regression tests via comment on the pull request.
Also removed our npm `s3-cli` because I don't feel super comfortable passing AWS creds to a package that we're not auditing or pinning.

Report visual regression test results

---

.env.production
.env.staging
package-lock.json
package.json

Resolves department-of-veterans-affairs/vets-contrib#325

Load API docs from corresponding vets-api environment for portal

---

src/content/release-notes/03-12-2019-release-notes.mdx

This PR is to create a new `src/content/release-notes` directory, along with a placeholder release note.
In https://github.com/department-of-veterans-affairs/vets-contrib/issues/1456, a link to this folder will be added from the `Updates` tab within the developer portal.

Create release-notes directory and placeholder release note

---

src/content/releaseNotes/facilities.mdx

Finishes [#1885](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1885)

Add facilities csv fix release note

---

src/content/releaseNotes/health.mdx

This PR fixes a typo in the Health API release notes.

Health release notes fix

---

src/components/SwaggerDocs.tsx

If metadata exists, load the current version based on it
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2587

Fix bug related to initial load + metadata

---

src/apiDefs/benefits.ts
src/content/releaseNotes/benefits.mdx

Minor last minute changes to Benefits Intake

Benefits Minor release note changes

---

src/containers/ApplyForm.tsx

closes ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/2767

change url for signup button

---

package-lock.json
package.json

resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2903

Upgrade caused weird fields to show up

---

src/content/releaseNotes/benefits.mdx

for https://github.com/department-of-veterans-affairs/vets-contrib/issues/2846

Add release note for validation page size

---

src/components/ApiCard.tsx
src/components/ApiPageReleaseNotes.tsx
src/components/Banner.tsx
src/components/Footer.tsx
src/components/NavBar.tsx
src/components/PageContent.tsx
src/components/SideNav.tsx
src/components/VeteransCrisisLine.tsx
src/containers/ApiKeyAuth.tsx
src/containers/ApplyForm.tsx
src/containers/ApplySuccess.tsx
src/containers/AuthorizationDocs.tsx
src/containers/Beta.tsx
src/containers/Explore.tsx
src/containers/Home.tsx
src/containers/News.tsx
src/containers/OAuth.tsx
src/containers/QuickstartPage.tsx
src/containers/ReleaseNotes.tsx
src/content/apiDocs/index.ts
src/utils/validators.ts
src/visualRegressionTest.ts
tslint.json

@mjlumetta has pointed out missing semicolons on a few recent PRs but we're all reluctant to clutter up already big diffs. This updates our tslint config to always include semicolons and adds in the missing ones.

Add semicolons

---

src/apiDefs/health.ts
src/content/apiDocs/health/legacyHealthIntro.mdx
src/content/apiDocs/index.ts
tslint.ci.json
tslint.json

the FHIR APIs are enabled everywhere

Remove FHIR checks in content and API definitions

---

src/content/releaseNotes/benefits.mdx

Minor release notes dealing with ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/3096
- Add release note for #3096

Adding release notes

---

src/containers/ApplyForm.tsx

in reference to https://lighthouseva.slack.com/archives/CEXC8GV2S/p1569948668238100

Fix form fields in ApplyForm

---

src/base.scss

https://github.com/department-of-veterans-affairs/vets-contrib/issues/2893

fix global a styles

---

src/components/Footer.scss
src/components/Footer.tsx

https://github.com/department-of-veterans-affairs/vets-contrib/issues/2893
Formation doesn't seem to have styles for .usa-footer-logo defined. Created a `va-api-footer-logo` class and added padding.

Fix footer

---

src/base.scss
src/components/CardLink.scss
src/components/Search.scss
src/components/Search.tsx

https://github.com/department-of-veterans-affairs/vets-contrib/issues/2893

Fix header spacing

---

src/content/apiDocs/health/argonautDeprecatedNotice.mdx

use updated description from Andrew

Use updated Argonaut deprecation text

---

src/base.scss
src/components/NavBar.scss
src/components/VeteransCrisisLine.scss

https://github.com/department-of-veterans-affairs/vets-contrib/issues/2893

Override 16px base font size from formation

---

config/polyfills.js
package-lock.json
package.json

`new URL` Breaks in IE11 -- This fixes that 
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/3215

URL polyfill for ie11

---

src/containers/support/SupportContactUsForm.scss
src/containers/support/SupportContactUsForm.tsx

part of https://github.com/department-of-veterans-affairs/vets-contrib/issues/3011

Use VADS in SupportContactUsForm and Support in general

---

src/components/GroupedAccordions.scss
src/components/GroupedAccordions.test.tsx
src/components/GroupedAccordions.tsx

https://github.com/department-of-veterans-affairs/vets-contrib/issues/3011
last one off `adopt-vads`

Use VADS styles in GroupedAccordions

---

src/base.scss
src/components/Header.scss
src/components/Header.tsx

Reverts department-of-veterans-affairs/developer-portal#251
accidentally merged without updating screenshots

Revert "Use VADS in Header"

---

src/components/NavBar.tsx

Add missing flag around menu elements.
https://app.zenhub.com/workspaces/developervagov-5ac272fff41bfa50c0e46c48/issues/department-of-veterans-affairs/vets-contrib/3509

Fix Appeals appearing in mobile nav in production

---

src/containers/documentation/swaggerPlugins/CurlForm.tsx

resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/3564

Refactor and make sure that we're meeting requirements

---

src/containers/ApplySuccess.tsx

https://github.com/department-of-veterans-affairs/vets-contrib/issues/3717

Fix va-forms signup

---

src/content/apiDocs/facilities/facilitiesReleaseNotes.mdx

Addresses https://github.com/department-of-veterans-affairs/vets-contrib/issues/3833 by adding a release note.

Add release note for VISN

---

README.md
src/containers/documentation/SwaggerDocs.tsx
src/containers/documentation/swaggerPlugins/CurlForm.tsx
src/containers/documentation/swaggerPlugins/VersionSelector.ts
src/reducers/api-versioning.ts

this PR addresses issue: https://github.com/department-of-veterans-affairs/vets-contrib/issues/3844

get the real version number in addition to the pseudo 'current' version

---

src/containers/documentation/swaggerPlugins/CurlForm.tsx

https://github.com/department-of-veterans-affairs/vets-contrib/issues/3944

Remove swagger 2 support

---

src/containers/documentation/swaggerPlugins/CurlForm.tsx

Reverts department-of-veterans-affairs/developer-portal#300

Revert "Remove swagger 2 support"

---

src/apiDefs/data/verification.ts
src/containers/documentation/DocumentationRoot.tsx
src/content/apiDocs/verification/verificationReleaseNotes.mdx

https://github.com/department-of-veterans-affairs/vets-contrib/issues/4022

Add Vet Conf to docs

---

src/apiDefs/data/benefits.ts
src/apiDefs/data/categories.ts
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-benefits-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-benefits-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-benefits-properly-3-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-health-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-properly-3-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-release-notes-properly-3-snap.png

alphabetize navbar (move vaForms up). alphabetize Benefits subnavbar (move Intake down)
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/4176

Sort NavBar and sub-NavBars

---

.env.dev

Reverting dev configs

---

src/containers/Home.tsx

Reference from Ticket https://vasdvp.atlassian.net/browse/DASH-161
- Change text on the portal to match Ticket wording

Updating Sandbox Migration message

---

src/containers/Home.tsx
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-3-snap.png

This PR changes the styling of the sandbox migration alert based on UX work by Carey Otto. It overrides some VADS styling on the alert box component to remove the gold top border and make the entire alert background light gold. This was accomplished using VADS utility classes.
For https://vajira.max.gov/browse/API-208.

Improve sandbox migration alert

---

src/content/apiDocs/facilities/facilitiesReleaseNotes.mdx

Added Facilities API release note to document the new features for Facilities API:  the additional services of Podiatry and Nutrition, and the addition of operating status (normal, notice, limited, closed) and additional information flags.

Added Facilities release note, additional services and operating status

---

src/containers/documentation/swaggerPlugins/CurlForm.tsx

resolves https://vajira.max.gov/browse/API-960

Remove `dev` and `staging` From Curl Generator

---

src/content/apiDocs/oauthTechnical.mdx

Changed documentation to show that the state parameter is a required parameter.

API-979-required-state-parameter

---

src/content/apiDocs/benefits/claimsReleaseNotes.mdx
src/content/apiDocs/health/communityCareReleaseNotes.mdx
src/content/apiDocs/health/fhirAPIReleaseNotes.mdx
src/content/apiDocs/health/urgentCareReleaseNotes.mdx
src/content/apiDocs/verification/veteranVerificationReleaseNotes.mdx

Per API-1197, added release note highlighting new support for `prompt: login` parameter as part of the Authorization flow for OAuth applications.
Change also documented in the Authorization section of the developer portal documentation.
https://developer.va.gov/explore/verification/docs/authorization

Added OAuth prompt login support release note.

---

public/google42fbb5f81dacc35d.html
public/google54216d2a67e162ea.html

This PR corrects the new verification file for the Google Search Console. When I clicked the verification link last time I did not realize that I was automatically logged in using my personal account. This verification file is for my Ad Hoc Google account.
PR that added my personal account: https://github.com/department-of-veterans-affairs/developer-portal/pull/375

Change Google Search Console owner

---

src/containers/apply/SelectedApis.tsx
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-apply-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-apply-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-apply-properly-3-snap.png

Group related checkboxes into a fieldset and update the aria-label to allow for assistive devices to better read the section of the form.
https://vajira.max.gov/browse/API-155

Group related checkboxes in fieldset [API-155]

---

src/containers/documentation/ApiDocumentation.tsx
src/openAPISpec/OpenAPISpec.tsx
src/openAPISpec/components/OpenAPIContents.tsx
src/openAPISpec/components/index.ts
src/openAPISpec/index.ts
src/openAPISpec/package-lock.json
src/openAPISpec/package.json
src/openAPISpec/state/actions.ts
src/openAPISpec/state/index.ts
src/openAPISpec/state/reducers.ts
src/openAPISpec/state/types.ts
src/store.ts
src/types/index.ts
tslint.json

first PR for [API-1267](https://vajira.max.gov/browse/API-1267). creates a pseudo-package in `src/openAPISpec`.
this PR adds the basis for the OpenAPI component by creating a set of Redux actions and reducers to load thee 
- not really going to test this one since it's a proof-of-concept
- not necessary because it's a proof of concept
- did a quick review and ran an aXe scan

First crack at a proof-of-concept OpenAPI component

---

src/containers/documentation/swaggerPlugins/CurlForm.tsx

Added `aria-label` to both the API key and Bearer Token fields for better s

API-135 Added aria-labels to API and Bearer Token fields

---

src/content/apiDocs/facilities/facilitiesReleaseNotes.mdx

Added release note for new Facilities API endpoint.
Implementation ticket: https://vajira.max.gov/browse/API-1823

API-1969- Update Release Notes for Facilities API

---

src/content/apiDocs/health/fhirAPIReleaseNotes.mdx

Added R4 release note to Health APIs.

Added R4 Release Note

---

.github/CODEOWNERS

This PR adds @department-of-veterans-affairs/lighthouse-koala as an equal codeowner for this repository.
All checks N/A

Add koala as equal codeowners

---

package-lock.json

fixes 1 Dependabot alert and partially but not entirely resolves another.
* fixed, high severity: `node-forge` must be >= 0.10.0
- used to be 0.9.0
- reinstalling `webpack-dev-server` with no upgrade fixed it (`node-forge` is a dependency of a dependency of `webpack-dev-server`
* ~mitigated, low severity: `node-fetch` must be >= 2.6.1~
- ~was 1.7.3 under `swagger-ui` and 2.6.0 under `msw`~
- ~upgraded `msw` to 0.21.2~
- ~upgraded `swagger-ui` to 3.34.0~
* ~this fixed the version of `node-fetch` under `swagger-client`, but it didn't fix another under `react` because `swagger-ui` uses React 15 (yikes)~
**edit:** once again, Swagger UI is terrible, so gonna deal with the low severity `node-fetch` issue in a subsequent PR.
n/a - no functional changes. do manual testing to ensure dev server, …

Fix Dependabot alert for node-forge by reinstalling webpack-dev-server

---

package-lock.json
src/__mocks__/openAPIData.test.json
src/containers/documentation/ApiDocumentation.test.tsx
src/containers/documentation/SwaggerDocs.tsx
tsconfig.json
tslint.json

completes [API-1317](https://vajira.max.gov/browse/API-1317).
adds unit tests for `ApiDocumentation`. these are testing pretty basic features of our Swagger documentation. it uses the new React Testing Library and MSW Node tools to construct the tests.
* PR is only adding tests
* n/a - no UI changes
is this a good level of tests to start with? are the tests meaningful?

Add basic unit tests for ApiDocumentation

---

src/components/crisisLine/VeteransCrisisLine.tsx
src/containers/documentation/ApiPage.tsx
src/hooks/ModalController.tsx
src/types/images.d.ts

API-2496: https://vajira.max.gov/browse/API-2496
Updated the two components to use React Hooks
- ApiPage
- VeteransCrisisLine
Note that we plan to update ApiPage to use hooks for obtaining it's routing properties so I left its PropTypes as an empty object, since it won't be taking any in the future. https://vajira.max.gov/browse/API-2650
- [N/A] Tests added or updated for change
- [N/A] Docs updated
- [N/A] Accessibility concerns have been considered and addressed
- I created a custom hook for the modal on VeteransCrisisLine. Wondering if we should make an effects folder to pull any custom effects out for reuse later on - or at least to clean up the files. Any thoughts on that? If people agree I can go ahead and do that under this PR.

Api 2496: Hook migration for ApiPage, VeteransCrisisLine

---

Jenkinsfile
src/containers/apply/ApplyForm.tsx
src/containers/documentation/DocumentationRoot.e2e.ts

This should allow Jenkins to post visual regressions to PR comments again

API-1214: Update Jenkins to post visual regressions

---

src/components/CardLink.tsx
src/components/CodeWrapper.tsx
src/components/PageHeader.tsx

Migration of CardLink, CodeWrapper, & PageHeader components from classes to hooks/arrow functions.
- [N/A] Tests added or updated for change
- [N/A] Docs updated
- [N/A] Accessibility concerns have been considered and addressed
All feedback welcome.

API-2534: Hooks Migration CardLink, CodeWrapper, & PageHeader Components

---

src/containers/documentation/swaggerPlugins/VersionActions.ts
src/containers/documentation/swaggerPlugins/VersionReducers.ts
src/containers/documentation/swaggerPlugins/VersionSelect.tsx
src/containers/documentation/swaggerPlugins/VersionSelector.ts
src/containers/documentation/swaggerPlugins/types.ts

fixes ESLint errors in the files for the Swagger UI version select component and its associated actions, reducers, and selectors for [API-1323](https://vajira.max.gov/browse/API-1323).
- [n/a] Tests added or updated for change
- [n/a] Accessibility concerns have been considered and addressed

Fix ESLint errors in Swagger API version plugins

---

src/containers/documentation/DocumentationRoot.tsx

Implemented Router 5 useParams to replaced Router 4 RouteComponentProps ⛱️ 
- [ n/a  ] Tests added or updated for change
- [ n/a ] Docs updated
- [ n/a ] Accessibility concerns have been considered and addressed
All feedback is welcome.

API 2910: Update Documentation Root to use Route Hooks

---

src/containers/Beta.tsx
src/containers/BetaSuccess.tsx
src/containers/DisabledApplyForm.tsx
src/containers/News.test.tsx
src/containers/News.tsx
src/containers/NotFound.tsx

fixes ESLint errors in the root of the `src/containers` directory for [API-1323](https://vajira.max.gov/browse/API-1323).
- [n/a] Tests added or updated for change
- [n/a] Accessibility concerns have been considered and addressed
can we get rid of `Beta`??? 🙏 🙏 🙏

Fix ESLint errors in containers root directory

---

src/containers/Home.tsx
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-2-snap.png

[API-209](https://vajira.max.gov/browse/API-209)
Removed the "Are you a vet" banner from the home page. 
Jest image snapshots have been updated

Remove "are you a vet" banner from the developer portal

---

src/types/index.ts

Missed an import from a previous PR (somehow)
- [ na ] Tests added or updated for change
- [ na ] Docs updated
- [ na ] Accessibility concerns have been considered and addressed

removed import

---

src/apiDefs/data/benefits.ts

This PR completes [API-3435](https://vajira.max.gov/browse/API-3435). It adds the newly exposed Claims Attributes OAS link. Can be confirmed working by visiting the documentation page for Claims Attributes in the DEV bundle.

Update Claims Attributes doc link

---

Jenkinsfile
Makefile
package-lock.json

validated that the `npm audit` steps in both CI jobs are working for [API-3138](https://vajira.max.gov/browse/API-3138). while I was playing around with that, I decided to tweak the audit level to be "moderate" and to run `npm audit fix`.
- [n/a] ~Tests added or updated for change~
- [n/a] ~Docs updated~
- [n/a] ~If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated~
- [n/a] ~If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated~
- [n/a] ~Accessibility concerns have been considered and addressed~
- [n/a] ~If you've made any UI changes, you've run an axe check using the axe …

Bump npm audit level to "moderate" for stricter security auditing

---

src/containers/publishing/Publishing.test.tsx
src/containers/publishing/Publishing.tsx
src/containers/publishing/components/publishingOnboarding/PublishingOnboarding.test.tsx
src/containers/publishing/components/publishingOnboarding/PublishingOnboarding.tsx
src/containers/publishing/components/publishingOnboarding/index.ts
src/e2eHelpers.ts
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-api-publishing-process-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-api-publishing-process-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-api-publishing-process-properly-3-snap.png

This adds in the How publishing works page to the new api publishing section
[API-4462](https://vajira.max.gov/browse/API-4462)

Api 4462/how publishing works page

---

src/components/index.ts
src/components/navBar/NavBar.test.tsx
src/components/navBar/NavBar.tsx
src/components/subNav/SubNav.test.tsx
src/components/subNav/SubNav.tsx
src/components/subNav/SubNavEntry.test.tsx
src/components/subNav/SubNavEntry.tsx
src/containers/publishing/Publishing.test.tsx
src/containers/publishing/Publishing.tsx

This PR adds API Publishing to the main navigation as described in [API-4442](https://vajira.max.gov/browse/API-4442). It also refactors the mobile subnav currently used for Documentation into its own component so it could be easily reused for API Publishing.

Api 4442/update main navigation

---

package-lock.json
src/containers/documentation/DocumentationRoot.e2e.ts
src/containers/documentation/DocumentationRoot.tsx

Story: [API-4636](https://vajira.max.gov/browse/API-4636)
Adding a redirect from old auth docs to the new docs with vet verification preselected.

Redirect for old vet verification auth docs to the new auth docs

---

src/App.tsx
src/components/groupedAccordions/GroupedAccordions.tsx
src/containers/publishing/Publishing.tsx
src/containers/publishing/components/publishingExpecations/PublishingExpectations.test.tsx
src/containers/publishing/components/publishingExpecations/PublishingExpectations.tsx
src/containers/publishing/components/publishingExpecations/index.ts
src/content/publishing/expectations/authentication.mdx
src/content/publishing/expectations/documentation.mdx
src/content/publishing/expectations/index.ts
src/content/publishing/expectations/modernization.mdx
src/content/publishing/expectations/monitoring.mdx
src/content/publishing/expectations/security.mdx
src/content/publishing/expectations/support.mdx
src/content/publishing/expectations/versioning.mdx
src/types/md.d.ts

This PR supports [API-4440](https://vajira.max.gov/browse/API-4440) by adding an API Expectations page.
Because there was so much content, I opted to use markdown files (`.mdx`). In regards to testing that the markdown is being correctly loaded: our Jest configuration does not currently handle loading markdown. I explored trying to make that a reality, but unfortunately, with packages that are currently available (`jest-mdx-loader` and `jest-transformer-mdx` were the two I tested), it's not possible to load the markdown files for testing—at least not possible in a "non-hacky" way.
At some point in the future if we want to test markdown content properly across the entire developer-portal, I would recommend looking into adapting the custom fork we have of the `markdown-component-loader` to …

API-4440 - API Publishing Expectations page

---

Dockerfile
package-lock.json
package.json

Immer high vulnerability in react-dev-utils(dev dependency) is blocking PR builds. This PR add the force resolution package to force the immer version that does not contain the vulnerability
All feedback is welcome.

Fixed immer vulnerability with force resolutions for transitive dependencies

---

src/content/apiDocs/vaForms/vaFormsReleaseNotes.mdx

Release notes for va_form_administration Forms API field
- [X ] Docs updated

Mark.viterna/api 5594 va form administration rn

---

src/content/apiDocs/benefits/benefitsIntakeReleaseNotes.mdx

Release notes for Benefits Intake v0 sunsetting

---

src/content/apiDocs/benefits/claimsReleaseNotes.mdx

Adds release note for changes in this pr: https://github.com/department-of-veterans-affairs/vets-api/pull/6256
https://vajira.max.gov/browse/API-5876
Structure and verbiage looks good.

API-5876: Add release note for change

---

package-lock.json
package.json

https://vajira.max.gov/browse/API-159
Adds aria-label attributes to select dropdowns by way of [this PR to Swagger UI](https://github.com/swagger-api/swagger-ui/pull/7133)
Check to ensure that all dropdowns in the swagger-ui sections include an aria-label field.

API-159 Update swagger-ui to gain aria-label attributes

---

src/content/apiDocs/benefits/claimsReleaseNotes.mdx

Adds a few release notes for changes deploying today
https://vajira.max.gov/browse/API-6454
https://vajira.max.gov/browse/API-6192
https://vajira.max.gov/browse/API-6434

Several release notes for tickets deploying today

---

src/content/apiDocs/vaForms/vaFormsReleaseNotes.mdx

Release notes for Forms API

---

src/content/apiDocs/health/fhirAPIReleaseNotes.mdx

FHIR Health API Release note for additional Identifiers

---

src/content/apiDocs/benefits/benefitsIntakeReleaseNotes.mdx

These notes should not be released until Monday, 05/24/2021.

Release notes - Turning back on name validation

---

src/apiDefs/data/verification.ts

[API-4352](https://vajira.max.gov/browse/API-4352)
Change the address validation docs url to point to S3 bucket that docserver uploads to

change docs url for address validation

---

package-lock.json
package.json
src/components/crisisLine/VeteransCrisisLine.test.tsx
src/components/crisisLine/VeteransCrisisLine.tsx
src/components/groupedAccordions/GroupedAccordions.tsx
src/containers/apply/ApplyForm.tsx
src/containers/documentation/ApiNotFoundPage.tsx
src/containers/documentation/ApiPage.tsx
src/containers/documentation/CategoryPage.tsx
src/containers/publishing/components/publishingExpecations/PublishingExpectations.tsx
src/containers/releaseNotes/CategoryReleaseNotes.tsx
src/containers/support/ContactUsAlertBox.tsx
src/types/@department-of-veterans-affairs/component-library/index.d.ts
src/types/@department-of-veterans-affairs/formation-react/index.d.ts

The @department-of-veterans-affairs/formation-react library has been deprecated in favor of @department-of-veterans-affairs/component-library. This PR updates developer-portal to use the new package, as described in [API-6716](https://vajira.max.gov/browse/API-6716).

Update deprecated @department-of-veterans-affairs/formation-react dependency

---

src/content/apiDocs/benefits/benefitsIntro.mdx
src/content/apiDocs/benefits/index.ts
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-benefits-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-release-notes-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-release-notes-properly-2-snap.png

Update documentation verbiage to make it clear the claims we provide are not medical.
https://vajira.max.gov/browse/API-6750

API-6750: Update description for Benefits Claims API

---

package-lock.json
package.json

Story: [API7512](https://vajira.max.gov/browse/API-7512)
NPM dependency upgrade. Quarterly maintenance
First of a few PRs to upgrade dependencies.

Api 7512/npm dependencies - 1

---

src/apiDefs/data/verification.ts

[API-7652](https://vajira.max.gov/browse/API-7652)
Added veteran confirmation to docserver and migrated the dev portal url to it

API-7652 point veteran confirmation docs to docserver S3

---

package-lock.json
package.json

Update to `prismjs` to deal with npm audit issue

Update prismjs for npm audit

---

src/apiDefs/data/verification.ts

This PR is for [API-7645](https://vajira.max.gov/browse/API-7645). It updates the veteran verification API OAS url so that it points to the OAS that is transformed by Docserver.

Update veteran verification API OAS url

---

src/content/apiDocs/health/communityCareReleaseNotes.mdx

Updated Release Notes for veteran PACT status

---

src/components/cardLink/CardLink.scss
src/containers/Home.scss
src/containers/Home.tsx
src/content/apiDocs/health/index.ts
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-the-homepage-properly-3-snap.png

tweaks to the home page left over from the redesign. completes [API-8832](https://vajira.max.gov/browse/API-8832).
TODO: visited style for pseudo-link in cards.

Make small style cleanups to home page

---

package-lock.json
package.json
src/containers/Home.tsx
src/containers/consumerOnboarding/DemoPrep.tsx
src/containers/consumerOnboarding/RequestProductionAccess.tsx
src/containers/consumerOnboarding/RequestSandboxAccess.tsx
src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.tsx
src/containers/documentation/DocumentationOverview.tsx
src/content/apiDocs/facilities/index.ts
src/content/news.yml
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-apply-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-apply-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-apply-properly-3-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-request-sandbox-access-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-request-sandbox-access-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-request-sandbox-access-properly-3-snap.png

This PR addresses numerous typos, incorrect case, boldness, and page link issues within the new consumer docs pages. None of this will actually be accessible until the consumer docs flag is switched which is planned for later this week.
I do not believe these changes impact any of the test cases.
Almost everything was just very simple text content changes and href links to new pages. I don't think this work should impact anything else, but would appreciate review!

Api 9027/onboarding docs punchlist

---

src/containers/consumerOnboarding/WorkingWithOurAPIs.tsx
src/content/publishing/expectations/monitoring.mdx

Updating Sandbox SLA verbiage
`onboarding/working-with-lighthouse-apis#status-alerts`
`api-publishing/expectations` under Monitoring

API-9172 change sandbox sla verbiage

---

package-lock.json

ran `npm install` to update dependencies of dependencies in `package-lock.json`. unblocks PRs in this repo by fixing security check failures in the CI job.

Resolve high severity vulnerability for tar

---

src/apiDefs/data/verification.ts

Add metadata URL for Veteran Verification API so that v1 will show up in the dev environment for [API-9570](https://vajira.max.gov/browse/API-9570)

Add metadata URL for veteran verification API

---

src/apiDefs/data/facilities.ts
src/apiDefs/query.test.ts

This PR is for [API-9815](https://vajira.max.gov/browse/API-9815) - it updates the Facilities API description so that documentation will be fetched according to the metadata JSON provided by Docserver.

Add metadata url for Facilities API

---

src/apiDefs/data/vaForms.ts

Story: [API-9816](https://vajira.max.gov/browse/API-9816)
This PR adds the metadata url to the Forms API Description

Add metadata to forms api def

---

src/containers/consumerOnboarding/ProductionAccess.tsx

This ticket comments out the 508 Compliance Modal. UX and Marmoset are going to do more research on the 508 compliance question and modal. Until then, that code is commented out, so that whenever that is done, we can quickly make the changes.

Commented out the 508 Compliance Modal

---

src/apiDefs/data/verification.ts
src/apiDefs/query.test.ts

This PR is for [API-9823](https://vajira.max.gov/browse/API-9823) - it updates the Veteran Confirmation API description so that documentation will be fetched according to the metadata JSON provided by Docserver.

Api 9823/veteran confirmation metadata

---

src/containers/consumerOnboarding/RequestProductionAccess.tsx
src/containers/consumerOnboarding/components/productionAccessForm/BasicInformation.tsx
src/containers/support/Support.tsx

[https://vajira.max.gov/browse/API-9610](API-9610)
[https://vajira.max.gov/browse/API-9605](API-9605)
[https://vajira.max.gov/browse/API-9602](API-9602)
*Content only changes (4)
- [N/A ] Tests added or updated for change
- [ N/A] Docs updated
- [N/A ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
- [ N/A] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [N/A ] Accessibility concerns have been considered and addressed
- [ Y] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues
Have I implemented the …

API-9610, API-9605, API-9602

---

src/containers/consumerOnboarding/ProductionAccess.tsx
src/containers/consumerOnboarding/components/productionAccessForm/TechnicalInformation.tsx
src/types/forms/productionAccess.ts

This PR adds the is508Compliant question answer in the Production Access form to the payload for the backend. This PR also addresses [API-9755](https://vajira.max.gov/browse/API-9755) and makes the PII/PHI and exposing Veteran data related questions text areas as shown in this [Figma File](https://www.figma.com/file/9sOD2GDAsyNTayvOqKlcJV/API-3854-Consumer?node-id=1315%3A479)

is508Compliance question is part of payload to the backend.  PII related questions are text areas now

---

src/containers/support/ContactUsAlertBox.tsx

- Replace deprecated URL (https://iris.custhelp.va.gov/app/ask) with the updated route (https://ask.va.gov/)

[API-10774] Submit a Question URL Update for Veteran Redirect Banner

---

.github/workflows/new-release.yml

https://vajira.max.gov/browse/API-9848
Bad trigger on the last merge. (sadly this work is a PR > merge > check results type of situation)

Push not merge

---

.github/workflows/new-release.yml

https://vajira.max.gov/browse/API-9848
Move auth to before the first aws cli call.

API-9848 - Change placement of AWS login

---

package-lock.json
package.json
src/base.accessibility.ts
src/components/codeWrapper/CodeWrapper.scss

https://vajira.max.gov/browse/API-3737
Package update allows the color test to work properly. The issue revolved around horizontal scrolling code sampled that had light colored text immediately next to the white background of the page. Resolved that with a small color gradient to give a color gap and also gives a nice visual queue that the text continues beyond the edge of the bounding box.

API-3737 - Update jest-axe to resolve accessibility test issue

---

src/containers/documentation/AuthorizationDocs.tsx

https://vajira.max.gov/browse/API-11492
Fixes a bug on the Authorization listing page where zooming out in Safari would cause the layout to slightly break. 
Also, apparently, eslint seems to have new ideas about how this file is laid out. [This](https://github.com/department-of-veterans-affairs/developer-portal/compare/api-11492/safari-zoom-bug?expand=1#diff-0f46db682c137edaed04832d77f0cc1387b38d67d6087ed88f9b36835838e696L24-R21) is the only substantive change.

[API-11492] Fix width issue on Safari

---

src/content/apiDocs/benefits/claimsReleaseNotes.mdx

Adds information about an enum update in claims v1

Add release note for benefits claims endpoints

---

src/content/apiDocs/benefits/claimsReleaseNotes.mdx

Adds information about an enum update in ClaimsApi v1.

[API-11988] - ClaimsApi - Update release notes

---

test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-benefits-docs-claims-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-benefits-docs-claims-properly-2-snap.png

Follow on to API-11518
Just a couple updates to visual regressions

A pair of visual regression updates

---

src/content/apiDocs/health/fhirAPIReleaseNotes.mdx

Veteran Health API - reference range changes release note

---

src/apiDefs/data/benefits.ts
src/apiDefs/query.test.ts
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-client-credentials-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-client-credentials-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-client-credentials-properly-3-snap.png

This PR adds missing CCG info for the Benefits Claims API and updates tests as needed. Thanks @dbrown-va for adding the missing information!

Add missing ccg aud to Benefits Claims API definition

---

src/components/oauthDocs/acg/BuildingOIDCContent.tsx
src/components/oauthDocs/acg/ScopesContent.tsx

Story:  [API-12703](https://vajira.max.gov/browse/API-12703)
The PGD API was listed in the selector dropdown on the Authorization Code Flow page. This PR will fix that.

Remove PGD from API selector in prod

---

package-lock.json
src/content/apiDocs/benefits/claimsReleaseNotes.mdx

- Updates Benefits ClaimsApi Release notes to announce addition of new "RRD" value for `specialIssues` in Form526 submissions.
[API-11705](https://vajira.max.gov/browse/API-11705)

[API-11705] - Claims Api - Update Release Notes

---

.github/workflows/new-release.yml

https://vajira.max.gov/browse/API-12405
Was part of building out this ticket and isn't working as expected after merge so just removing it.

Remove fork blocker as it was broken

---

src/components/codeWrapper/CodeWrapper.scss
src/styles/swagger.scss
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-benefits-docs-claims-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-benefits-docs-claims-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-benefits-docs-claims-properly-3-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-health-docs-quickstart-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-health-docs-quickstart-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-health-docs-quickstart-properly-3-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-prepare-for-and-complete-a-demo-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-prepare-for-and-complete-a-demo-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-prepare-for-and-complete-a-demo-properly-3-snap.png

https://vajira.max.gov/browse/API-12768
This will allow code samples to be height limited so that large JSON responses don't cause the page to become incredibly long, especially on mobile.

[API-12768] - Apply max heights

---

src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.tsx
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-request-sandbox-access-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-request-sandbox-access-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-onboarding-request-sandbox-access-properly-3-snap.png

Fixing a content merge bug on the first step of the consumer onboarding process.
Removed the highlighted content section in this [Figma file](https://www.figma.com/file/4lp9S6kwdbXzXim72LGMNE/AUDIT?node-id=969%3A59).
[https://vajira.max.gov/browse/API-13016](https://vajira.max.gov/browse/API-13016)

API-13016 - fixing content merge bug

---

.eslintrc.js
package-lock.json
package.json
src/App.tsx
src/registerServiceWorker.ts

https://vajira.max.gov/browse/API-3327
This eslint plugin will help us keep our promises standardized wherever possible and help with good clean code.

[API-3327] - Add eslint-plugin-promise

---

src/content/apiDocs/health/fhirAPIReleaseNotes.mdx

Update Release Notes to include Practitioner by ICN search.

Health API- Practitioner by ICN Search Release Note

---

src/apiDefs/data/loanGuaranty.ts

https://vajira.max.gov/browse/API-12233
LGY API is now on docserver. This just updates the portal to point at the docserver url instead of directly at the api.

API-12233: Update LGY Loan Guaranty on Portal to use OAS from Docserver - DEV STAGING PROD

---

src/content/apiDocs/benefits/benefitsReferenceDataReleaseNotes.mdx

Benefits Reference Data was recently released to production. These release notes are the more up-to-date version.
https://vajira.max.gov/browse/API-13223
Axe scan ran and this PR introduces no new accessibility concerns.

Benefits reference data update release notes

---

.github/CODEOWNERS
.github/dependabot.yml
.github/labeler.yml
.github/workflows/assets/maintenance-request.md
.github/workflows/auto-deploy-to-production.yml
.github/workflows/auto-label-content-prs.yml
.github/workflows/create-auto-deploy-maintenance-request.yml

https://vajira.max.gov/browse/API-12829
Tweaks and updates based on the [first generated MR](https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/1156). Also included is `labeler.yml` which will attempt to _roughly_ label content updates like Release Notes and News so that people contributing to the repo won't have more work on their plates.

[API-12829] - Fixes for the MR template for auto deploys

---

package-lock.json
src/components/header/Header.tsx
src/content/apiDocs/benefits/benefitsReferenceDataReleaseNotes.mdx
src/types/@department-of-veterans-affairs/component-library/index.d.ts

- Add va-alert banner to header and display only on facilities docs page
- Add props interface for va-alert component
- N/A
- N/A

[API-13220] Facilities Versioning Banner

---

src/content/apiDocs/benefits/claimsReleaseNotes.mdx

Release notes for the changes made by https://github.com/department-of-veterans-affairs/vets-api/pull/9112
~- [ ] Tests added or updated for change~
~- [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated~
~- [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated~
~- [ ] Accessibility concerns have been considered and addressed~
~- [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues~

API-13230: Release notes for Claims API

---

src/content/apiDocs/health/fhirAPIReleaseNotes.mdx

Changing US State Name in addresses to US State Code in R4 as per specification.

R4 US State Name to State Code Change

---

package-lock.json
package.json

https://vajira.max.gov/browse/API-3323
Adds `eslint-plugin-jest` and also resolves an npm audit issue with `prismjs`.

[API-3323] - Add eslint-plugin-jest

---

package-lock.json
package.json
unit.jest.config.js

https://vajira.max.gov/browse/API-3875
Adding code coverage reporting to `test:unit:ci` with thresholds that approximately match what is currently covered. If the coverage drops below it will fail the test. A [future ticket](https://vajira.max.gov/browse/API-13022) is already written to cover increasing code coverage overall.

[API-3875] - Adding code coverage to test:unit:ci

---

package-lock.json
src/apiDefs/data/loanGuaranty.ts

Adds LGY Guaranty Remittance to CCG OAuth docs

API-13909: Add LGY Guaranty Remittance API to CCG Auth Page

---

.eslintrc.js
package-lock.json
package.json
src/components/formField/FieldSet/FieldSet.tsx
src/components/oauthDocs/acg/BuildingOIDCContent.tsx
src/components/oauthDocs/acg/ScopesContent.tsx
src/containers/documentation/AuthorizationCodeGrant/AuthorizationCodeGrantDocs.tsx
src/containers/documentation/ClientCredentialsGrant/ClientCredentialsGrantDocs.tsx
src/containers/documentation/SwaggerDocs.tsx

This PR adds `eslint-plugin-react-redux` and fixes any new issues caught by the new linting rules.

Api 3326/add eslint-plugin-react-redux

---

src/components/header/Header.tsx

https://vajira.max.gov/browse/API-14314
Adds a banner to the benefits claims page mentioning a future depreciation is coming.

[API-14314] - Add future benefits claims depreciation banner

---

README.md
src/components/header/Header.tsx

https://vajira.max.gov/browse/API-14708
Facilities API new version is delayed. Banner verbiage needed to be updated to reflect that.

API-14689: Update Banner Verbiage for Facilities API

---

package-lock.json
package.json

Resolves an npm audit issue with `moment`.

NPM audit fix for moment.js

---

src/types/constants/index.ts

Fixes issue with contact us path to LCMS.
Related PR regarding the same change to the rev-proxy:
https://github.com/department-of-veterans-affairs/devops/pull/11068

fix support "contact us" path

---

src/content/apiDocs/appeals/decisionReviewReleaseNotes.mdx

[API-13511](https://vajira.max.gov/browse/API-13511)
Publish the Release Notes describing the new Supplemental Claims endpoints.  Darcy has approved the following:
Release Notes:
On MONTH DD, YYYY we added 5 new endpoints to the [Decision Reviews API. ](https://dev-developer.va.gov/explore/appeals/docs/decision_reviews?version=current)These endpoints allow you to: 
Submit a Supplemental Claim (VA Form 20-0995). Structured data is submitted to the API which generates the most recent version of the PDF claim. 
Upload supporting evidence documents in PDF form with the Supplemental Claim.

API-13511-supplemental-claims

---

src/containers/consumerOnboarding/ProductionAccess.tsx
src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.tsx
src/containers/support/ContactUsForm/ContactUsForm.tsx

Hoping setting `secure` will allow LCMS to pick up the value in production.

add secure to cookie creation

---

src/containers/consumerOnboarding/ProductionAccess.tsx
src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.tsx
src/containers/support/ContactUsForm/ContactUsForm.tsx
src/types/constants/index.ts

Thread is old but mentions the rails requirement of having the exact path defined within the cookie:
https://stackoverflow.com/a/3838487/3013472

specify backend path in cookie

---

src/apiDefs/data/health.ts

https://vajira.max.gov/browse/API-15366

API-15366 Added patient/Encounter.read to oauth table.

---

src/content/apiDocs/health/fhirAPIReleaseNotes.mdx

May17OrganizationUpdate.mdx

---

src/content/apiDocs/benefits/claimsReleaseNotes.mdx

- Updates Benefits ClaimsApi Release Notes to mention that `claimant_ssn` is a new optional attribute on the POST "/forms/0966" endpoint

[API-15889] - ClaimsApi - Update Release Notes

---

.github/workflows/pr-builds.yml
.github/workflows/pr-requires-label.yml
config/webpack.config.prod.js
package-lock.json

https://vajira.max.gov/browse/API-7760
Just trying some things to get the PR builds working on @imcgonigle's PR #1061

[API-7760] - upgrade webpack to v5 pr builds

---

src/containers/consumerOnboarding/components/sandbox/SandboxAccessForm.tsx

Error message verbiage says everything is fine when everything is not fine.

improve error message

---

src/components/header/Header.tsx

https://vajira.max.gov/browse/API-16551
This PR merges on June 15th so it can deploy the morning of June 16.

[API-16551] - Remove benefits claims v0 banner (Merge on 6/15)

---

package-lock.json
package.json

https://vajira.max.gov/browse/API-16742
At minimum updates the `shell-quote` package but ideally updates the parent package and doesn't rely on a resolution to patch.

[API-16742] - Fix critical shell-quote vulnerability

---

src/content/apiDocs/health/fhirAPIReleaseNotes.mdx

July 6 _lastUpdated Update

---

src/apiDefs/data/verification.ts

https://vajira.max.gov/browse/API-17688
Simple update to the service name for VA Letter Generator from `veteran-letters` to `va-letter-generator`.

[API-17688] - Update VA Letter Generator service name

---

src/content/apiDocs/health/fhirAPIReleaseNotes.mdx

August 11 _lastUpdated Update

---

.github/workflows/cypress-smoketest.yml

https://vajira.max.gov/browse/API-18737
Resolve intentional error after the first test run succeeded and sent the proper notification to #vaapi-alerts

[API-18737] - Fixed smoketest after intentional failure

---

src/containers/consumerOnboarding/components/productionAccessForm/BasicInformation.tsx
src/containers/consumerOnboarding/validationSchema.ts
src/types/forms/productionAccess.ts

Closes https://vajira.max.gov/browse/API-21027
This PR updates the appName form field description and makes it a required field.

[API-21027] Update App name form field

---

src/apiDefs/query.test.ts
src/apiDefs/query.ts
src/components/formField/TextField/TextField.tsx
src/containers/consumerOnboarding/ProductionAccess.tsx
src/containers/consumerOnboarding/components/productionAccessForm/BasicInformation.tsx
src/containers/consumerOnboarding/validationSchema.ts
src/types/forms/productionAccess.ts

Closes https://vajira.max.gov/browse/API-18988

[API-18988] - Fix fields in production access form

---

package-lock.json
package.json

This PR pins minimatch to version 3.1.2

Pin minimatch to version 3.1.2

---

public/data/platform-backend/v0/providers/transformations/legacy.json
src/components/oauthDocs/acg/ScopesContent.tsx
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-authorization-code-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-authorization-code-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-authorization-code-properly-3-snap.png

https://vajira.max.gov/browse/API-21149
A quick audit for the listed scopes found two that were missing. This adds the scope descriptions to the auth docs.

[API-21149] - Audit scopes on Veteran Verification v2

---

src/apiDefs/schema.ts

https://vajira.max.gov/browse/API-20650
In prep for the new information architecture this schema change will allow for the backend to start sending the `categoryUrlFragment` as a part of the each API's definition. This will drastically reduce complexity on the front end and facilitate better usage of fuse.js for searching.
After LPB is updated to push down this value this schema change will be updated to no longer be an optional property.

Add optional categoryUrlFragment to APIDescription

---

src/components/oauthDocs/ccg/GeneratingJWTContent.tsx
src/components/oauthDocs/ccg/GoodToKnow.tsx
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-client-credentials-properly-1-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-client-credentials-properly-2-snap.png
test/image_snapshots/visual-regression-test-ts-visual-regression-test-renders-explore-authorization-docs-client-credentials-properly-3-snap.png

- Add the disclaimer to "Good To Know" section and in "aud" table row

[API-23395] Update CCG docs disclaimer

---

config/webpack.config.prod.js

This PR fixes the script and link src attributes so they point to the correct location.

Add leading '/' to script and style paths

---

src/components/oauthDocs/ccg/RetrievingTokenContent.tsx

Original Issue :: [API-25142](https://vajira.max.gov/browse/API-25142)
Updates the CCG grant page verbiage to match requested changes.

[API-25142] - Update CCG grant page verbiage

---

.github/workflows/assets/maintenance-request.md

https://vajira.max.gov/browse/API-25263
Related to https://github.com/department-of-veterans-affairs/lighthouse-devops-support/pull/2355
Simple update to MR template. Checkbox remains unchecked as this is just for the very first deploy to an SLA'd environment and not each new release going to an SLA'd environment.

[API-25263] - Update MR template

---

.github/workflows/auto-deploy-to-production.yml
.github/workflows/codeql.yml
.github/workflows/create-auto-deploy-maintenance-request.yml
.github/workflows/cypress-tests.yml
.github/workflows/generate-visual-regressions.yml
.github/workflows/new-release.yml
.github/workflows/npm-checks.yml
.github/workflows/pr-builds-privileged.yml
.github/workflows/pr-builds.yml
.github/workflows/visual-regressions-privileged.yml
.github/workflows/visual-regressions-unprivileged.yml

https://vajira.max.gov/browse/API-25502
Some aspects of our GitHub Actions workflows are being removed at the [end of May](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). With the migration away from those this also removes any remaining actions based on node12 which is being removed at some point [this summer](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

[API-25502] - Resolve future GitHub Action depreciations

---

.github/workflows/assets/maintenance-request.md

Quick change to MR assignees requested by Leeroy Jenkles.

[API-25263] - Change MR assignees

---

src/content/news.yml

Original Issue :: [API-25298](https://vajira.max.gov/browse/API-25298)
- Updates 2 broken links on the DevPortal's "News" view.

[API-25298] - Update broken links on DevPortal

---

src/components/header/Header.tsx

https://vajira.max.gov/browse/API-25406

Add deprecation alert for vet confirmation API

---

.github/workflows/assets/maintenance-request.md

Teams are unsupported as an assignee for issues. 🤦‍♂️

[API-25263] - MR approvers goes back to a list

---

.github/workflows/assets/maintenance-request.md
.github/workflows/create-auto-deploy-maintenance-request.yml

[API-25263] - Fix MR assignees

---

src/Routes.tsx
src/__mocks__/fakeCategories.tsx
src/apiDefs/query.test.ts
src/components/apiSelector/APISelector.tsx
src/components/formField/MultiEntryTextField/EditInputField.test.tsx
src/components/sideNav/SideNavEntry.tsx
src/containers/documentation/ApiDocumentation.tsx
src/containers/documentation/ApiOverviewPage.tsx
src/containers/documentation/ApiPage.test.tsx
src/containers/documentation/ApiPage.tsx
src/containers/documentation/DocumentationRoot.tsx
src/containers/providers/IntegrationGuide.test.tsx
src/containers/publishing/Publishing.test.tsx
src/containers/publishing/components/publishingIntroduction/PublishingIntroduction.test.tsx
src/containers/support/Support.test.tsx
src/types/index.ts

https://vajira.max.gov/browse/API-23997
Provides the base skeleton pages to allow more parallel work to be done across the auth docs, api docs, overview, release notes, and sandbox access pages. Basically any pages that used to allow for a dropdown to select and API and change the content still include those for now. The removal of those will come in subsequent tickets.

[API-23997] Skeleton pages functioning

---

cypress/fixtures/legacy.json
public/data/platform-backend/v0/providers/transformations/legacy.json

[API-26845] Remove CAIRN endorsement

---

cypress/e2e/containers/documentation/ExploreRoot.cy.js
src/components/exploreApiCard/ExploreApiCard.scss
src/components/exploreApiCard/ExploreApiCard.tsx
src/components/index.ts
src/components/pageHeader/PageHeader.tsx
src/containers/documentation/DocumentationRoot.tsx
src/containers/documentation/ExploreRoot.scss
src/containers/documentation/ExploreRoot.test.tsx
src/containers/documentation/ExploreRoot.tsx

- Add page header content
- Add placeholder for filter section
- Add list of apis linking to corresponding docs pages

[API-24008] Explore skeleton

---

package-lock.json
package.json

https://jira.devops.va.gov/browse/API-23465
Simply updates Swagger to be able to process OAS 3.1 spec files.

[API-23465] - Update to OAS 3.1 capable Swagger UI

---

src/components/header/Header.tsx

- Add conditional banner to Header for VSHE

[API-27237] VSHE Deprecation Banner

---

src/components/sideNav/SideNav.scss

https://jira.devops.va.gov/browse/API-23997
One line fix to account for multi-line API names in the side nav

[API-13997] - Fix side nav long api name

---

src/utils/deprecationBannerHelper.tsx

Original Issue :: [API-27355](https://jira.devops.va.gov/browse/API-27355)
- Updates the verbiage on the deprecation banner for the Facilities API.

[API-27355] - Update FacilitiesAPI deprecation banner verbiage

---

package-lock.json
package.json
src/containers/documentation/ExploreRoot.scss
src/containers/documentation/ExploreRoot.tsx

https://jira.devops.va.gov/browse/API-24011
Update Explore page to allow filtering of APIs via fuzzy search.

[API-24011] - Explore apis fuzzy search

---

src/components/exploreApiCard/ExploreApiTags.scss
src/containers/documentation/ExploreRoot.scss

- flex wrap tags to prevent breaking words
- lessen padding on explore container on mobile

Fix explore filter tag styling

---

src/containers/about/Overview.tsx

**Original Issue**
[API-27780](https://jira.devops.va.gov/browse/API-27780)
- Temporarily remove the "you'll be in good company" section of the DevPortal ["About"](https://developer.va.gov/about) page.

[API-22780] - Temporarily remove the "you'll be in good company" section

---

src/Routes.tsx
src/components/exploreApiCard/ExploreApiCard.tsx
src/containers/ErrorPage.test.tsx
src/containers/ErrorPage.tsx
src/containers/documentation/ApiOverviewPage.tsx
src/containers/documentation/ApiPage.test.tsx
src/containers/documentation/ApiPage.tsx
src/containers/documentation/AuthorizationCodeGrant/AuthorizationCodeGrantDocs.tsx
src/containers/documentation/ClientCredentialsGrant/ClientCredentialsGrantDocs.tsx
src/containers/documentation/DocumentationRoot.tsx
src/containers/documentation/ReleaseNotes.tsx
src/containers/documentation/RequestSandboxAccess.tsx
src/containers/documentation/swaggerPlugins/VersionSelect.tsx
src/containers/documentation/swaggerPlugins/WrapHighlightCode.tsx

This adds back the 404 page handling and includes needed updates that adhere to site structure changes.

Add back 404 page

---

src/apiDefs/query.ts
src/components/apiFilters/ApiFilters.tsx
src/containers/documentation/ExploreRoot.test.tsx

This PR removes deprecated APIs from explore page

Only display active APIs on explore page

---

src/components/exploreApiCard/ExploreApiTags.tsx
src/utils/generateFilterTags.ts

- update generateFilterTags to abide by new guidelines
- Add manual checks for outlier API conditions
- Change tags schema to include 'showLock' property

[API-27821] Update tag restricted access rules

---

src/components/apiFilters/TopicFilters.tsx
src/utils/generateFilterTags.ts

An alternative solution to using an object to map names was to chain `.replace('APIs', '').replace('Veteran', '').trim()`. Let me know which of these two solutions is preferred.

Update topic filter names to use abbreviated form

---

cicd/buildspec-deploy.yml

This hopefully resolves the redirects not posting to s3 as expected. Unfortunately no real way to test besides doing it "live" in dev / staging.

[API-24015] - Syntax changes to redirects script

---

cicd/buildspec-deploy.yml

Needed to be within the environment loop to get the right variables.

[API-24015] - Redirect all environments properly

---

cicd/buildspec-deploy.yml

Trying to figure out a very unhelpful error within CodeBuild.
`/codebuild/output/tmp/script.sh: line 105: syntax error: bad substitution`

[API-24015] - More debugging for redirects

---

cicd/buildspec-deploy.yml
src/components/SiteRedirects.tsx

[API-27929] Add auth docs redirects

---

cypress/e2e/containers/documentation/AuthorizationCodeGrantDocs.cy.js
package-lock.json
package.json
src/components/oauthDocs/acg/AuthCodeGrantContent.test.tsx
src/components/oauthDocs/acg/AuthCodeGrantContent.tsx
src/components/oauthDocs/acg/BuildingOIDCContent.tsx
src/components/oauthDocs/acg/IdToken.tsx
src/components/oauthDocs/acg/PageLinks.tsx
src/components/oauthDocs/acg/ScopesContent.tsx
src/containers/consumerOnboarding/components/productionAccessForm/SelectedApis.tsx

Update instances of Auth Code Flow w/ Auth Code Grant

---

src/apiDefs/query.test.ts
src/apiDefs/query.ts
src/components/apiFilters/TopicFilters.tsx

[API-28038](https://jira.devops.va.gov/browse/API-28038)

[API-28038] Topic filter displays number of active APIs

---

package-lock.json
package.json

https://jira.devops.va.gov/browse/API-27858
Covers 3 of the 4 currently open dependabot PRs. The one for `msw` appears to be a breaking change and will require more work to upgrade as is or to replace with a different form of request mocks.

[API-27858] - Package updates

---

config/webpack.config.prod.js

- Original Issue [API-27895](https://jira.devops.va.gov/browse/API-27895)
- Removes unused ~var~ const detected by VA CodeScan

[API-27895] - CodeScan - Remove unused variable

---

cypress/e2e/containers/consumerOnboarding/ProductionAccess.cy.js
src/components/formField/MultiEntryTextField/EditInputField.tsx
src/containers/consumerOnboarding/validationSchema.ts

[Jira Ticket (API-28027)](https://jira.devops.va.gov/browse/API-28027)
This PR fixes the validation for the Status Update Email list field

Fix validation for the statusUpdateEmails field

---

config/paths.js

Original Issue :: [API-27890](https://jira.devops.va.gov/browse/API-27890)
- removes useless conditional identified by [VA CodeScan](https://github.com/department-of-veterans-affairs/developer-portal/security/code-scanning/5).
- simplifies conditional logic

[API-27890] - Remove useless conditional and simplify code

---

config/jest/setupJestPostEnv.js
src/containers/support/ContactUsForm/ContactUsForm.tsx
src/utils/ScrollToFirstError.tsx

[API-28415](https://jira.devops.va.gov/browse/API-28415)

[API-28415] Scroll to first error on support form submission

---

src/containers/documentation/swaggerPlugins/VersionSelect.tsx

This was part of #1188 but lost in the IA merge.

Re-add display banner on API revision select

---

src/containers/documentation/swaggerPlugins/VersionSelect.tsx

Includes work for https://jira.devops.va.gov/browse/API-28414

Display banner for all API version changes and update FHIR regex

---

src/components/apiBreadcrumbs/ApiBreadcrumbs.test.tsx
src/components/apiBreadcrumbs/ApiBreadcrumbs.tsx
src/components/apiFilters/ApiFilters.test.tsx
src/components/apiFilters/ApiFilters.tsx

[API-28413](https://jira.devops.va.gov/browse/API-28413)

[API-28413] Update breadcrumb navigation to explore APIs with filters

---

package.json
scripts/build.js
scripts/start.js

https://jira.devops.va.gov/browse/API-24651
Package isn't necessary on it's own so changing to use the one under `react-dev-tools` instead.

[API-24651] - Remove chalk package

---

.github/workflows/notify-security-alerts.yml

Original Issue :: [API-28910](https://jira.devops.va.gov/browse/API-28910)
- Tweaks the structure of the "Notify Security Alerts" GHA workflow so that it properly notifies us when an alert has been detected.

[API-28910] - Fix Notify Security Alerts GHA workflow

---

src/utils/apiAlerts.tsx

[Jira Ticket (API-29266)](https://jira.devops.va.gov/browse/API-29266)
This PR updates the Facilities API banner content.

API-29266/Update Facilities API with Banner in ALL environments

---

.github/emass.json

Original Issue :: [API-29431](https://jira.devops.va.gov/browse/API-29431)
- Updates the system owner values in the `emass.json` file.

[API-29431] - Update system owner values in emass.json file

---

public/index.html

Original Issue :: [API-28873](https://jira.devops.va.gov/browse/API-28873)
- Adds Google Tag Manager integration
- This will allow us to add/edit/remove Google Analytics event tracking with very little to no-code going forward.

[API-28873] - Add GoogleTagManager

---

src/containers/consumerOnboarding/RequestProductionAccess.tsx

https://jira.devops.va.gov/browse/API-30402
Add an alert to the page leading into the prod access form discussing the timeline on gaining production access.

[API-30402] - Alert for prod access timelime

---

src/utils/apiAlerts.tsx

https://jira.devops.va.gov/browse/API-30664
Add a deactivation notice to the Patient Health API overview page.

[API-30664] - Add Argonaut deactivation banner to Patient Health

---

src/components/oauthDocs/ccg/RetrievingTokenContent.tsx
src/utils/ccgLaunchContextHelper.test.tsx
src/utils/ccgLaunchContextHelper.tsx

- Update CCG launch context description for Guaranty Remittance and Loan Review APIs

[API-31131] Update CCG Launch Description

---

src/components/exploreApiCard/ExploreApiCard.scss
src/components/exploreApiCard/ExploreApiCard.tsx

https://jira.devops.va.gov/browse/API-29806

[API-29806] - API cards update for screen readers

---

src/components/navBar/NavBar.test.tsx
src/components/navBar/NavBar.tsx

https://jira.devops.va.gov/browse/API-29741

[API-29741] - Add aria-label for API status link (SR)

---

src/utils/apiAlerts.tsx

Original Issue :: [API-31634](https://jira.devops.va.gov/browse/API-31634)
- Updates verbiage on the banner for the Veteran Service History and Eligibility API

[API-31634] - Update Veteran Service History API banner

---

src/containers/about/platformMetrics.ts

https://jira.devops.va.gov/browse/API-32455

[API-32455] - Update metrics on About page

---

src/utils/apiAlerts.tsx

Update Facilities API deactivation date in the page banner.

[API-32575] - Update facilities API deactivation date

---

src/services/lpb.ts

https://jira.devops.va.gov/browse/API-31641
Missing the header in the request causing 403 errors.

[API-31641] - Fix missing csrf header

---

src/components/pageContent/PageContent.tsx

https://jira.devops.va.gov/browse/API-32601

[API-32601] Fix link to API standards

---

.github/workflows/cypress-tests.yml
.github/workflows/generate-visual-regressions.yml
.github/workflows/visual-regressions-unprivileged.yml

This fixes the GPG errors currently occurring in our GitHub actions that use the cypress/included image.

fix: use newer cypress image

---

src/containers/consumerOnboarding/RequestProductionAccess.scss
src/containers/consumerOnboarding/RequestProductionAccess.tsx

Reverts department-of-veterans-affairs/developer-portal#1451

Revert "[API-34585] Update privacy policy and tos for prod form"
